/* tslint:disable */
/* eslint-disable */
/**
 * admin-api 관리자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetFilesUploadResDto
 */
export interface GetFilesUploadResDto {
  /**
   *
   * @type {string}
   * @memberof GetFilesUploadResDto
   */
  path: string
  /**
   *
   * @type {string}
   * @memberof GetFilesUploadResDto
   */
  url: string
  /**
   * Presigned URL로 전송 시 입력해야할 field 값
   * @type {object}
   * @memberof GetFilesUploadResDto
   */
  fields: object
}
