/* tslint:disable */
/* eslint-disable */
/**
 * admin-api 관리자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PatchAdministratorReqDto
 */
export interface PatchAdministratorReqDto {
  /**
   *    * master: 최고관리자   * manager: 매니저
   * @type {string}
   * @memberof PatchAdministratorReqDto
   */
  role: PatchAdministratorReqDtoRoleEnum
  /**
   *
   * @type {string}
   * @memberof PatchAdministratorReqDto
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof PatchAdministratorReqDto
   */
  nickname: string
  /**
   *
   * @type {string}
   * @memberof PatchAdministratorReqDto
   */
  expireDate?: string
  /**
   *
   * @type {boolean}
   * @memberof PatchAdministratorReqDto
   */
  enabled: boolean
  /**
   *
   * @type {string}
   * @memberof PatchAdministratorReqDto
   */
  password?: string
  /**
   *
   * @type {Array<number>}
   * @memberof PatchAdministratorReqDto
   */
  groupIds?: Array<number>
}

export const PatchAdministratorReqDtoRoleEnum = {
  Master: 'master',
  Manager: 'manager',
} as const

export type PatchAdministratorReqDtoRoleEnum =
  (typeof PatchAdministratorReqDtoRoleEnum)[keyof typeof PatchAdministratorReqDtoRoleEnum]
