/* tslint:disable */
/* eslint-disable */
/**
 * admin-api 관리자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostAdministratorReqDto
 */
export interface PostAdministratorReqDto {
  /**
   *    * master: 최고관리자   * manager: 매니저
   * @type {string}
   * @memberof PostAdministratorReqDto
   */
  role: PostAdministratorReqDtoRoleEnum
  /**
   *
   * @type {string}
   * @memberof PostAdministratorReqDto
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof PostAdministratorReqDto
   */
  nickname: string
  /**
   *
   * @type {string}
   * @memberof PostAdministratorReqDto
   */
  expireDate?: string
  /**
   *
   * @type {boolean}
   * @memberof PostAdministratorReqDto
   */
  enabled: boolean
  /**
   *
   * @type {string}
   * @memberof PostAdministratorReqDto
   */
  password: string
}

export const PostAdministratorReqDtoRoleEnum = {
  Master: 'master',
  Manager: 'manager',
} as const

export type PostAdministratorReqDtoRoleEnum =
  (typeof PostAdministratorReqDtoRoleEnum)[keyof typeof PostAdministratorReqDtoRoleEnum]
