packages:
  - apps/*
  - packages/data/*
  - packages/system/*
  - packages/ui/*
  - packages/bridge

catalog:
  '@types/node': ^22
  '@types/mime-types': ^2
  axios: ^1
  dayjs: ^1
  dotenv: ^16
  eslint: ^9
  es-toolkit: ^1
  path-to-regexp: ^8
  prettier: ^3
  prettier-plugin-tailwindcss: ^0.6
  tsup: ^8
  typescript: ^5.8.3
  vite: ^6
  vite-plugin-svgr: ^4
  zod: ^3

catalogs:
  react:
    '@hookform/resolvers': ^5
    '@mdx-js/react': ^3
    '@mdx-js/rollup': ^3
    '@tailwindcss/vite': ^4
    '@tailwindcss/postcss': ^4
    '@tanstack/react-query': ^5
    '@tanstack/react-query-devtools': ^5
    '@tanstack/react-router': ^1
    '@tanstack/react-router-devtools': ^1
    '@tanstack/react-table': ^8
    '@tanstack/router-plugin': ^1
    '@types/react': ^19
    '@types/react-dom': ^19
    '@vitejs/plugin-react-swc': ^3
    class-variance-authority: ^0.7
    clsx: ^2
    lucide-react: latest
    next-themes: ^0.4
    postcss: ^8
    react: 19.0.0
    react-dom: 19.0.0
    react-hook-form: ^7
    tailwindcss: ^4
    tw-animate-css: ^1
    tailwind-merge: ^3

  next:
    '@mdx-js/loader': ^3
    '@next/bundle-analyzer': ^15
    '@next/mdx': ^15
    '@svgr/webpack': ^8
    '@types/mdx': ^2
    next: ^15
    next-auth: ^5.0.0-beta.28
    next-intl: ^4
    server-only: ^0.0.1
    jose: ^6

  ui:
    '@radix-ui/react-accordion': ^1
    '@radix-ui/react-alert-dialog': ^1
    '@radix-ui/react-aspect-ratio': ^1
    '@radix-ui/react-avatar': ^1
    '@radix-ui/react-checkbox': ^1
    '@radix-ui/react-collapsible': ^1
    '@radix-ui/react-dialog': ^1
    '@radix-ui/react-dropdown-menu': ^2
    '@radix-ui/react-label': ^2
    '@radix-ui/react-popover': ^1
    '@radix-ui/react-progress': ^1
    '@radix-ui/react-radio-group': ^1
    '@radix-ui/react-scroll-area': ^1
    '@radix-ui/react-select': ^2
    '@radix-ui/react-separator': ^1
    '@radix-ui/react-slider': ^1
    '@radix-ui/react-slot': ^1
    '@radix-ui/react-switch': ^1
    '@radix-ui/react-tabs': ^1
    '@radix-ui/react-toast': ^1
    '@radix-ui/react-toggle': ^1
    '@radix-ui/react-toggle-group': ^1
    '@radix-ui/react-tooltip': ^1
    cmdk: ^1
    sonner: ^2
    vaul: ^1
