packages:
  - apps/*
  - packages/data/*
  - packages/system/*
  - packages/ui/*
  - packages/bridge

publicHoistPattern:
  - 'expo'
  - 'expo-*'
  - '@expo/*'
  - '*expo-modules-core'
  - '*expo-modules-autolinking'
  - '*babel-preset-expo'
nodeLinker: hoisted

catalog:
  '@types/node': ^22
  '@types/mime-types': ^2
  axios: ^1
  dotenv: ^16
  eslint: ^9
  path-to-regexp: ^8
  prettier: ^3
  prettier-plugin-tailwindcss: ^0.6
  typescript: ^5.8.3
  vite: ^6
  vite-plugin-svgr: ^4
  zod: ^3

catalogs:
  react:
    '@tailwindcss/vite': ^4
    '@tanstack/react-query': ^5
    '@tanstack/react-router': ^1
    '@tanstack/router-plugin': ^1
    '@types/react': ^19
    '@types/react-dom': ^19
    '@vitejs/plugin-react-swc': ^3
    clsx: ^2
    lucide-react: latest
    react: 19.0.0
    react-dom: 19.0.0
    tailwindcss: ^4
    tw-animate-css: ^1
    tailwind-merge: ^3

  next:
    '@mdx-js/loader': ^3
    '@next/bundle-analyzer': ^15
    '@next/mdx': ^15
    '@svgr/webpack': ^8
    '@types/mdx': ^2
    next: ^15
    next-auth: ^5.0.0-beta.28
    next-intl: ^4
    server-only: ^0.0.1
    jose: ^6

  ui:
    '@radix-ui/react-alert-dialog': ^1
    '@radix-ui/react-dialog': ^1
