/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 답변 등록 응답 데이터
 * @export
 * @interface AnswerData
 */
export interface AnswerData {
  /**
   * 멤버 답변 ID
   * @type {number}
   * @memberof AnswerData
   */
  memberAnswerId?: number
}
