/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AnswerData } from './answer-data'

/**
 * 질문 답변 등록 성공 응답
 * @export
 * @interface AnswerSuccessResponse
 */
export interface AnswerSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof AnswerSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof AnswerSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof AnswerSuccessResponse
   */
  message?: string
  /**
   *
   * @type {AnswerData}
   * @memberof AnswerSuccessResponse
   */
  data?: AnswerData
}
