/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TermsResponseData } from './terms-response-data'

/**
 * 기본 리스트 응답 형식
 * @export
 * @interface BaseListSwaggerResponseTermsResponseData
 */
export interface BaseListSwaggerResponseTermsResponseData {
  /**
   * 응답 데이터 크기
   * @type {number}
   * @memberof BaseListSwaggerResponseTermsResponseData
   */
  size?: number
  /**
   * 페이지 번호
   * @type {number}
   * @memberof BaseListSwaggerResponseTermsResponseData
   */
  page?: number
  /**
   * 응답 데이터 리스트
   * @type {Array<TermsResponseData>}
   * @memberof BaseListSwaggerResponseTermsResponseData
   */
  list?: Array<TermsResponseData>
  /**
   * 전체 데이터 개수
   * @type {number}
   * @memberof BaseListSwaggerResponseTermsResponseData
   */
  totalCount?: number
}
