/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetMessagesByBookmarkResponse } from './get-messages-by-bookmark-response'

export interface BaseResponseGetMessagesByBookmarkResponse {
  requestId?: string
  success?: boolean
  message?: string
  data?: GetMessagesByBookmarkResponse
}
