/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 기본 응답 형식
 * @export
 * @interface BaseSwaggerResponse
 */
export interface BaseSwaggerResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof BaseSwaggerResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof BaseSwaggerResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof BaseSwaggerResponse
   */
  message?: string
  /**
   * 응답 데이터
   * @type {object}
   * @memberof BaseSwaggerResponse
   */
  data?: object
}
