/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface BookmarkDto {
  bookmarkId?: number
  content?: string
  type?: BookmarkDtoTypeEnum
  timestamp?: string
}

export const BookmarkDtoTypeEnum = {
  User: 'USER',
  Assistant: 'ASSISTANT',
  System: 'SYSTEM',
} as const

export type BookmarkDtoTypeEnum = (typeof BookmarkDtoTypeEnum)[keyof typeof BookmarkDtoTypeEnum]
