/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BaseListSwaggerResponseGetChatRoomListResponse } from './base-list-swagger-response-get-chat-room-list-response'

/**
 * 채팅방 리스트 조회 성공 응답
 * @export
 * @interface ChatRoomListSuccessResponse
 */
export interface ChatRoomListSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof ChatRoomListSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof ChatRoomListSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof ChatRoomListSuccessResponse
   */
  message?: string
  /**
   *
   * @type {BaseListSwaggerResponseGetChatRoomListResponse}
   * @memberof ChatRoomListSuccessResponse
   */
  data?: BaseListSwaggerResponseGetChatRoomListResponse
}
