/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 채팅 완료 응답 데이터
 * @export
 * @interface CompleteChatRoomData
 */
export interface CompleteChatRoomData {
  /**
   * 채팅방의 ID
   * @type {number}
   * @memberof CompleteChatRoomData
   */
  chatRoomId?: number
}
