/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CompleteChatRoomData } from './complete-chat-room-data'

/**
 * 채팅방 완료 성공 응답
 * @export
 * @interface CompleteChatRoomResponse
 */
export interface CompleteChatRoomResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof CompleteChatRoomResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof CompleteChatRoomResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof CompleteChatRoomResponse
   */
  message?: string
  /**
   *
   * @type {CompleteChatRoomData}
   * @memberof CompleteChatRoomResponse
   */
  data?: CompleteChatRoomData
}
