/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CoupleLinkData } from './couple-link-data'

/**
 * 커플 연결 성공 응답
 * @export
 * @interface CoupleLinkSuccessResponse
 */
export interface CoupleLinkSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof CoupleLinkSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof CoupleLinkSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof CoupleLinkSuccessResponse
   */
  message?: string
  /**
   *
   * @type {CoupleLinkData}
   * @memberof CoupleLinkSuccessResponse
   */
  data?: CoupleLinkData
}
