/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 채팅방 생성 응답 데이터
 */
export interface CreateChatRoomData {
  /**
   * 채팅방 ID
   */
  chatRoomId?: number
  /**
   * 채팅방 상태
   */
  chatRoomState?: CreateChatRoomDataChatRoomStateEnum
  /**
   * 생성 시간
   */
  createdAt?: string
}

export const CreateChatRoomDataChatRoomStateEnum = {
  Alive: 'ALIVE',
  Completed: 'COMPLETED',
  Deleted: 'DELETED',
} as const

export type CreateChatRoomDataChatRoomStateEnum =
  (typeof CreateChatRoomDataChatRoomStateEnum)[keyof typeof CreateChatRoomDataChatRoomStateEnum]
