/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 채팅 리스트 조회 완료 응답 데이터
 * @export
 * @interface GetChatRoomListResponse
 */
export interface GetChatRoomListResponse {
  /**
   * 채팅방의 ID
   * @type {number}
   * @memberof GetChatRoomListResponse
   */
  chatRoomId?: number
  /**
   * 채팅방 전체 요약
   * @type {string}
   * @memberof GetChatRoomListResponse
   */
  totalSummary?: string
  /**
   * 채팅방 상황 키워드
   * @type {string}
   * @memberof GetChatRoomListResponse
   */
  situationKeyword?: string
  /**
   * 채팅방 해결 키워드
   * @type {string}
   * @memberof GetChatRoomListResponse
   */
  solutionKeyword?: string
  /**
   * 채팅방 생성 시간
   * @type {string}
   * @memberof GetChatRoomListResponse
   */
  createdAt?: string
}
