/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 채팅 요약 조회 완료 응답 데이터
 * @export
 * @interface GetChatRoomSummaryData
 */
export interface GetChatRoomSummaryData {
  /**
   * 채팅방의 ID
   * @type {number}
   * @memberof GetChatRoomSummaryData
   */
  chatRoomId?: number
  /**
   * 채팅방 전체 요약
   * @type {string}
   * @memberof GetChatRoomSummaryData
   */
  totalSummary?: string
  /**
   * 채팅방 상황 요약
   * @type {string}
   * @memberof GetChatRoomSummaryData
   */
  summary?: string
  /**
   * 애착유형 설명
   * @type {string}
   * @memberof GetLoveTypeData
   */
  content?: string
  /**
   * 이미지 URL
   * @type {string}
   * @memberof GetLoveTypeData
   */
  imageUrl?: string
}
