/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BaseListSwaggerResponsePendingNotificationData } from './base-list-swagger-response-pending-notification-data'

/**
 * 멤버 미조회 알림 조회 성공 응답
 * @export
 * @interface GetPendingMemberNotificationSuccessResponse
 */
export interface GetPendingMemberNotificationSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof GetPendingMemberNotificationSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof GetPendingMemberNotificationSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof GetPendingMemberNotificationSuccessResponse
   */
  message?: string
  /**
   *
   * @type {BaseListSwaggerResponsePendingNotificationData}
   * @memberof GetPendingMemberNotificationSuccessResponse
   */
  data?: BaseListSwaggerResponsePendingNotificationData
}
