/* tslint:disable */

/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetUserCategoryResDto
 */
export interface GetUserCategoryResDto {
  /**
   * 카테고리명
   * @type {string}
   * @memberof GetUserCategoryResDto
   */
  name: string
  /**
   * 1차 카테고리 ID
   * @type {number}
   * @memberof GetUserCategoryResDto
   */
  parentId?: number
  /**
   * 생성일
   * @type {string}
   * @memberof GetUserCategoryResDto
   */
  createdAt: string
  /**
   * 수정일
   * @type {string}
   * @memberof GetUserCategoryResDto
   */
  updatedAt: string
  /**
   * 카테고리 차수
   * @type {number}
   * @memberof GetUserCategoryResDto
   */
  level: number
  /**
   * 최하위 카테고리 여부
   * @type {boolean}
   * @memberof GetUserCategoryResDto
   */
  last: boolean
  /**
   *
   * @type {number}
   * @memberof GetUserCategoryResDto
   */
  id: number
}
