/* tslint:disable */

/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GetAuthResDto
 */
export interface GetAuthResDto {
  /**
   *
   * @type {number}
   * @memberof GetAuthResDto
   */
  id: number
  /**
   * 개인 회원인 경우 회원명, 기업 회원인 경우 대표자명
   * @type {string}
   * @memberof GetAuthResDto
   */
  name?: string
}
