/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { GetLoveTypeData } from './get-love-type-data'

/**
 * 애착유형 조회 성공 응답
 * @export
 * @interface GetLoveTypeSuccessResponse
 */
export interface GetLoveTypeSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof GetLoveTypeSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof GetLoveTypeSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof GetLoveTypeSuccessResponse
   */
  message?: string
  /**
   *
   * @type {GetLoveTypeData}
   * @memberof GetLoveTypeSuccessResponse
   */
  data?: GetLoveTypeData
}
