/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { LoveType } from './love-type'

/**
 * 애착유형 조회 응답 데이터
 * @export
 * @interface GetLoveTypeData
 */
export interface GetLoveTypeData {
  /**
   *
   * @type {LoveType}
   * @memberof GetLoveTypeData
   */
  loveType?: LoveType
  /**
   * 애착유형 요약
   * @type {string}
   * @memberof GetLoveTypeData
   */
  summary?: string
  /**
   * 애착유형 설명
   * @type {string}
   * @memberof GetLoveTypeData
   */
  description?: string
  /**
   * 이미지 URL
   * @type {string}
   * @memberof GetLoveTypeData
   */
  imageUrl?: string
}
