/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { InviteCodeResponseData } from './invite-code-response-data'

/**
 * 멤버 초대 코드 성공 응답
 */
export interface GetInviteCodeSuccessResponse {
  /**
   * 요청 ID
   */
  requestId?: string
  /**
   * 성공 여부
   */
  success?: boolean
  /**
   * 응답 메시지
   */
  message?: string
  data?: InviteCodeResponseData
}
