/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 로그인 응답 데이터
 */
export interface LoginData {
  /**
   * 토큰 타입
   */
  grantType?: string
  /**
   * 액세스 토큰
   */
  accessToken?: string
  /**
   * 리프레시 토큰
   */
  refreshToken?: string
  /**
   * 멤버 상태
   */
  memberState?: string
}
