/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 애착 유형
 * @export
 * @interface LoveType
 */
export interface LoveType {
  /**
   *
   * @type {string}
   * @memberof LoveType
   */
  createdAt?: string
  /**
   *
   * @type {string}
   * @memberof LoveType
   */
  modifiedAt?: string
  /**
   *
   * @type {string}
   * @memberof LoveType
   */
  deletedAt?: string
  /**
   *
   * @type {number}
   * @memberof LoveType
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof LoveType
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof LoveType
   */
  content?: string
  /**
   *
   * @type {string}
   * @memberof LoveType
   */
  imageUrl?: string
  /**
   *
   * @type {number}
   * @memberof LoveType
   */
  weight?: number
}
