/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 멤버 정보 응답 데이터
 * @export
 * @interface MemberData
 */
export interface MemberData {
  /**
   * 멤버 상태
   * @type {string}
   * @memberof MemberData
   */
  memberState?: MemberDataMemberStateEnum
  /**
   * 연애 시작일
   * @type {string}
   * @memberof MemberData
   */
  loveStartDate?: string
  /**
   * 애착 유형 ID
   * @type {number}
   * @memberof MemberData
   */
  loveTypeId?: number
  /**
   * 애착 유형 제목
   * @type {string}
   * @memberof MemberData
   */
  loveTypeTitle?: string
  /**
   * 회피 비율
   * @type {number}
   * @memberof MemberData
   */
  avoidanceRate?: number
  /**
   * 불안 비율
   * @type {number}
   * @memberof MemberData
   */
  anxietyRate?: number
  /**
   * 닉네임
   * @type {string}
   * @memberof MemberData
   */
  nickname?: string
  /**
   * 이메일
   * @type {string}
   * @memberof MemberData
   */
  email?: string
}

export const MemberDataMemberStateEnum = {
  BeforeOnboarding: 'BEFORE_ONBOARDING',
  Alive: 'ALIVE',
  Deleted: 'DELETED',
} as const

export type MemberDataMemberStateEnum = (typeof MemberDataMemberStateEnum)[keyof typeof MemberDataMemberStateEnum]
