/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MessageDto {
  messageId?: number
  content?: string
  senderType?: MessageDtoSenderTypeEnum
  createdAt?: string
  isSaved?: boolean
}

export const MessageDtoSenderTypeEnum = {
  User: 'USER',
  Assistant: 'ASSISTANT',
  System: 'SYSTEM',
} as const

export type MessageDtoSenderTypeEnum = (typeof MessageDtoSenderTypeEnum)[keyof typeof MessageDtoSenderTypeEnum]
