/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PartnerMemberData } from './partner-member-data'

/**
 * 파트너 멤버 정보 조회 성공 응답
 * @export
 * @interface PartnerMemberInfoSuccessResponse
 */
export interface PartnerMemberInfoSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof PartnerMemberInfoSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof PartnerMemberInfoSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof PartnerMemberInfoSuccessResponse
   */
  message?: string
  /**
   *
   * @type {PartnerMemberData}
   * @memberof PartnerMemberInfoSuccessResponse
   */
  data?: PartnerMemberData
}
