/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 파트너 멤버 정보 응답 데이터
 * @export
 * @interface PartnerMemberData
 */
export interface PartnerMemberData {
  /**
   * 멤버 상태
   * @type {string}
   * @memberof PartnerMemberData
   */
  memberState?: PartnerMemberDataMemberStateEnum
  /**
   * 애착 유형
   * @type {string}
   * @memberof PartnerMemberData
   */
  loveTypeCategory?: PartnerMemberDataLoveTypeCategoryEnum
  /**
   * 회피 비율
   * @type {number}
   * @memberof PartnerMemberData
   */
  avoidanceRate?: number
  /**
   * 불안 비율
   * @type {number}
   * @memberof PartnerMemberData
   */
  anxietyRate?: number
  /**
   * 닉네임
   * @type {string}
   * @memberof PartnerMemberData
   */
  nickname?: string
}

export const PartnerMemberDataMemberStateEnum = {
  BeforeOnboarding: 'BEFORE_ONBOARDING',
  Alive: 'ALIVE',
  Deleted: 'DELETED',
} as const

export type PartnerMemberDataMemberStateEnum =
  (typeof PartnerMemberDataMemberStateEnum)[keyof typeof PartnerMemberDataMemberStateEnum]
export const PartnerMemberDataLoveTypeCategoryEnum = {
  StableType: 'STABLE_TYPE',
  AnxietyType: 'ANXIETY_TYPE',
  AvoidanceType: 'AVOIDANCE_TYPE',
  ConfusionType: 'CONFUSION_TYPE',
} as const

export type PartnerMemberDataLoveTypeCategoryEnum =
  (typeof PartnerMemberDataLoveTypeCategoryEnum)[keyof typeof PartnerMemberDataLoveTypeCategoryEnum]
