/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 상대 프로필 응답 데이터
 */
export interface PartnerProfileData {
  /**
   * 상대방 MBTI
   */
  personalityType?: string
  /**
   * 상대방 애착 유형
   */
  loveTypeCategory?: PartnerProfileDataLoveTypeCategoryEnum
  /**
   * 애착 유형 설명
   */
  description?: string
}

export const PartnerProfileDataLoveTypeCategoryEnum = {
  StableType: 'STABLE_TYPE',
  AnxietyType: 'ANXIETY_TYPE',
  AvoidanceType: 'AVOIDANCE_TYPE',
  ConfusionType: 'CONFUSION_TYPE',
  Unknown: 'UNKNOWN',
} as const

export type PartnerProfileDataLoveTypeCategoryEnum =
  (typeof PartnerProfileDataLoveTypeCategoryEnum)[keyof typeof PartnerProfileDataLoveTypeCategoryEnum]
