/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 과거 답변 상세 데이터
 * @export
 * @interface PastAnswerDto
 */
export interface PastAnswerDto {
  /**
   * 멤버 답변 ID
   * @type {number}
   * @memberof PastAnswerDto
   */
  memberAnswerId?: number
  /**
   * 답변 내용
   * @type {string}
   * @memberof PastAnswerDto
   */
  answer?: string
  /**
   * 답변한 멤버 닉네임
   * @type {string}
   * @memberof PastAnswerDto
   */
  memberNickname?: string
  /**
   * 답변 생성일시
   * @type {string}
   * @memberof PastAnswerDto
   */
  createdAt?: string
}
