/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AnswerDto } from './answer-dto'

/**
 * 과거 답변 조회 응답 데이터
 */
export interface PastAnswerData {
  /**
   * 질문 제목
   */
  title?: string
  /**
   * 질문 내용
   */
  content?: string
  /**
   * 질문 단계
   */
  level?: number
  /**
   * 답변 생성일시
   */
  createdAt?: string
  me?: AnswerDto
  partner?: AnswerDto
}
