/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PastAnswerData } from './past-answer-data'

/**
 * 질문 답변 조회 성공 응답
 * @export
 * @interface PastAnswerSuccessResponse
 */
export interface PastAnswerSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof PastAnswerSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof PastAnswerSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof PastAnswerSuccessResponse
   */
  message?: string
  /**
   *
   * @type {PastAnswerData}
   * @memberof PastAnswerSuccessResponse
   */
  data?: PastAnswerData
}
