/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 과거 질문 조회 응답 데이터
 * @export
 * @interface PastQuestionData
 */
export interface PastQuestionData {
  /**
   * 커플 질문 ID
   * @type {number}
   * @memberof PastQuestionData
   */
  coupleQuestionId?: number
  /**
   * 질문 제목
   * @type {string}
   * @memberof PastQuestionData
   */
  title?: string
  /**
   * 질문 내용
   * @type {string}
   * @memberof PastQuestionData
   */
  content?: string
  /**
   * 생성일시
   * @type {string}
   * @memberof PastQuestionData
   */
  createdAt?: string
}
