/* tslint:disable */
/* eslint-disable */
/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UserSetting } from './user-setting'

/**
 *
 * @export
 * @interface PatchUserReqDto
 */
export interface PatchUserReqDto {
  /**
   * business: 기업, individual: 개인
   * @type {string}
   * @memberof PatchUserReqDto
   */
  type: PatchUserReqDtoTypeEnum
  /**
   * 개인 회원인 경우 회원명, 기업 회원인 경우 대표자명
   * @type {string}
   * @memberof PatchUserReqDto
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof PatchUserReqDto
   */
  zipCode?: string
  /**
   *
   * @type {string}
   * @memberof PatchUserReqDto
   */
  address?: string
  /**
   *
   * @type {string}
   * @memberof PatchUserReqDto
   */
  addressDetail?: string
  /**
   *
   * @type {string}
   * @memberof PatchUserReqDto
   */
  lastLoggedAt?: string
  /**
   *
   * @type {boolean}
   * @memberof PatchUserReqDto
   */
  agreeReceiveEmail?: boolean
  /**
   *
   * @type {boolean}
   * @memberof PatchUserReqDto
   */
  agreeReceiveText?: boolean
  /**
   *
   * @type {string}
   * @memberof PatchUserReqDto
   */
  coordinate: string
  /**
   *
   * @type {UserSetting}
   * @memberof PatchUserReqDto
   */
  setting: UserSetting
}

export const PatchUserReqDtoTypeEnum = {
  Business: 'business',
  Individual: 'individual',
} as const

export type PatchUserReqDtoTypeEnum = (typeof PatchUserReqDtoTypeEnum)[keyof typeof PatchUserReqDtoTypeEnum]
