/* tslint:disable */

/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostAuthUserRegisterReqDto
 */
export interface PostAuthUserRegisterReqDto {
  /**
   *
   * @type {string}
   * @memberof PostAuthUserRegisterReqDto
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof PostAuthUserRegisterReqDto
   */
  accountId: string
  /**
   *
   * @type {string}
   * @memberof PostAuthUserRegisterReqDto
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof PostAuthUserRegisterReqDto
   */
  password: string
  /**
   *
   * @type {string}
   * @memberof PostAuthUserRegisterReqDto
   */
  phone: string
  /**
   *
   * @type {number}
   * @memberof PostAuthUserRegisterReqDto
   */
  categoryId: number
  /**
   * 마케팅 활용 동의 - 이메일
   * @type {boolean}
   * @memberof PostAuthUserRegisterReqDto
   */
  agreeEmail: boolean
  /**
   * 마케팅 활용 동의 - SMS
   * @type {boolean}
   * @memberof PostAuthUserRegisterReqDto
   */
  agreeSMS: boolean
  /**
   *
   * @type {string}
   * @memberof PostAuthUserRegisterReqDto
   */
  codeToken: string
}
