/* tslint:disable */

/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostVerificationResDto
 */
export interface PostVerificationResDto {
  /**
   *
   * @type {string}
   * @memberof PostVerificationResDto
   */
  codeToken: string
  /**
   *
   * @type {string}
   * @memberof PostVerificationResDto
   */
  expireAt: string
  /**
   *
   * @type {string}
   * @memberof PostVerificationResDto
   */
  code: string
}
