/* tslint:disable */

/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostAuthFindAccountIdReqDto
 */
export interface PostAuthFindAccountIdReqDto {
  /**
   *
   * @type {string}
   * @memberof PostAuthFindAccountIdReqDto
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof PostAuthFindAccountIdReqDto
   */
  phone?: string
  /**
   *
   * @type {string}
   * @memberof PostAuthFindAccountIdReqDto
   */
  businessNumber?: string
}
