/* tslint:disable */
/* eslint-disable */
/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PostAuthBusinessUserRegisterReqDtoInfo } from './post-auth-business-user-register-req-dto-info'

/**
 *
 * @export
 * @interface PostAuthBusinessUserRegisterReqDto
 */
export interface PostAuthBusinessUserRegisterReqDto {
  /**
   *
   * @type {string}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  accountId: string
  /**
   *
   * @type {string}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  password: string
  /**
   *
   * @type {string}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  phone: string
  /**
   *
   * @type {number}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  categoryId: number
  /**
   *
   * @type {string}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  email: string
  /**
   *
   * @type {PostAuthBusinessUserRegisterReqDtoInfo}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  businessInfo: PostAuthBusinessUserRegisterReqDtoInfo
  /**
   * 마케팅 활용 동의 - 이메일
   * @type {boolean}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  agreeEmail: boolean
  /**
   * 마케팅 활용 동의 - SMS
   * @type {boolean}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  agreeSMS: boolean
  /**
   *
   * @type {string}
   * @memberof PostAuthBusinessUserRegisterReqDto
   */
  codeToken: string
}
