/* tslint:disable */

/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostFilesUploadReqDto
 */
export interface PostFilesUploadReqDto {
  /**
   *
   * @type {string}
   * @memberof PostFilesUploadReqDto
   */
  type: PostFilesUploadReqDtoTypeEnum
  /**
   *
   * @type {string}
   * @memberof PostFilesUploadReqDto
   */
  kind: PostFilesUploadReqDtoKindEnum
  /**
   *
   * @type {string}
   * @memberof PostFilesUploadReqDto
   */
  path: string
}

export const PostFilesUploadReqDtoTypeEnum = {
  Image: 'image',
  File: 'file',
} as const

export type PostFilesUploadReqDtoTypeEnum =
  (typeof PostFilesUploadReqDtoTypeEnum)[keyof typeof PostFilesUploadReqDtoTypeEnum]
export const PostFilesUploadReqDtoKindEnum = {
  Users: 'users',
  Stores: 'stores',
  Posts: 'posts',
  Products: 'products',
  Etc: 'etc',
} as const

export type PostFilesUploadReqDtoKindEnum =
  (typeof PostFilesUploadReqDtoKindEnum)[keyof typeof PostFilesUploadReqDtoKindEnum]
