/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BaseListSwaggerResponseQuestionListData } from './base-list-swagger-response-question-list-data'

/**
 * 질문 리스트 조회 성공 응답
 * @export
 * @interface QuestionListSuccessResponse
 */
export interface QuestionListSuccessResponse {
  /**
   * 요청 ID
   * @type {string}
   * @memberof QuestionListSuccessResponse
   */
  requestId?: string
  /**
   * 성공 여부
   * @type {boolean}
   * @memberof QuestionListSuccessResponse
   */
  success?: boolean
  /**
   * 응답 메시지
   * @type {string}
   * @memberof QuestionListSuccessResponse
   */
  message?: string
  /**
   *
   * @type {BaseListSwaggerResponseQuestionListData}
   * @memberof QuestionListSuccessResponse
   */
  data?: BaseListSwaggerResponseQuestionListData
}
