/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 애착유형 등록 응답 데이터
 * @export
 * @interface RegisterLoveTypeData
 */
export interface RegisterLoveTypeData {
  /**
   * 애착 유형 ID
   * @type {number}
   * @memberof RegisterLoveTypeData
   */
  loveTypeId?: number
  /**
   * 애착 유형
   * @type {string}
   * @memberof RegisterLoveTypeData
   */
  title?: string
  /**
   * 애착유형 요약
   * @type {string}
   * @memberof RegisterLoveTypeData
   */
  summary?: string
  /**
   * 애착유형 설명
   * @type {string}
   * @memberof RegisterLoveTypeData
   */
  content?: string
  /**
   * 이미지 URL
   * @type {string}
   * @memberof RegisterLoveTypeData
   */
  imageUrl?: string
}
