/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { LoveType } from './love-type'

/**
 * 애착유형 등록 응답 데이터
 * @export
 * @interface RegisterLoveTypeData
 */
export interface RegisterLoveTypeData {
  /**
   *
   * @type {LoveType}
   * @memberof RegisterLoveTypeData
   */
  loveType?: LoveType
}
