/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 애착유형 등록 성공 응답
 */
export interface RegisterLoveTypeSuccessResponse {
  /**
   * 요청 ID
   */
  requestId?: string
  /**
   * 성공 여부
   */
  success?: boolean
  /**
   * 응답 메시지
   */
  message?: string
  /**
   * 응답 데이터
   */
  data?: object
}
