/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 채팅 응답 데이터
 * @export
 * @interface SendChatData
 */
export interface SendChatData {
  /**
   * 사용자가 보낸 메시지의 ID
   * @type {number}
   * @memberof SendChatData
   */
  messageId?: number
}
