/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { TermsDto } from './terms-dto'

/**
 *
 * @export
 * @interface SignUpRequestDto
 */
export interface SignUpRequestDto {
  /**
   *
   * @type {Array<TermsDto>}
   * @memberof SignUpRequestDto
   */
  terms?: Array<TermsDto>
  /**
   *
   * @type {string}
   * @memberof SignUpRequestDto
   */
  nickname: string
  /**
   *
   * @type {string}
   * @memberof SignUpRequestDto
   */
  loveStartDate: string
}
