/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 기본 응답 형식
 */
export interface SwaggerErrorResponse {
  /**
   * 요청 ID
   */
  requestId?: string
  /**
   * 에러 코드
   */
  code?: string
  /**
   * 성공 여부
   */
  success?: boolean
  /**
   * 응답 메시지
   */
  message?: string
}
