/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 약관 동의 정보 데이터
 * @export
 * @interface TermsData
 */
export interface TermsData {
  /**
   * 약관 ID
   * @type {number}
   * @memberof TermsData
   */
  termsId?: number
  /**
   * 약관 동의 여부
   * @type {boolean}
   * @memberof TermsData
   */
  isAgreed?: boolean
}
