/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TermsDto
 */
export interface TermsDto {
  /**
   *
   * @type {number}
   * @memberof TermsDto
   */
  termsId: number
  /**
   *
   * @type {boolean}
   * @memberof TermsDto
   */
  isAgreed: boolean
}
