/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 약관 내용 및 형식 데이터
 * @export
 * @interface TermsDetailsResponseData
 */
export interface TermsDetailsResponseData {
  /**
   * 해당 내용의 형식
   * @type {string}
   * @memberof TermsDetailsResponseData
   */
  type?: TermsDetailsResponseDataTypeEnum
  /**
   * 약관 내용
   * @type {string}
   * @memberof TermsDetailsResponseData
   */
  content?: string
}

export const TermsDetailsResponseDataTypeEnum = {
  Title: 'TITLE',
  Subtitle: 'SUBTITLE',
  Content: 'CONTENT',
} as const

export type TermsDetailsResponseDataTypeEnum =
  (typeof TermsDetailsResponseDataTypeEnum)[keyof typeof TermsDetailsResponseDataTypeEnum]
