/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateMemberRequestDto {
  nickname?: string
  relationshipStatus?: UpdateMemberRequestDtoRelationshipStatusEnum
  personalityType?: string
  otherPersonalityType?: string
}

export const UpdateMemberRequestDtoRelationshipStatusEnum = {
  InRelationship: 'IN_RELATIONSHIP',
  SeeingSomeone: 'SEEING_SOMEONE',
  Breakup: 'BREAKUP',
} as const

export type UpdateMemberRequestDtoRelationshipStatusEnum =
  (typeof UpdateMemberRequestDtoRelationshipStatusEnum)[keyof typeof UpdateMemberRequestDtoRelationshipStatusEnum]
