/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 멤버 정보 수정 응답 데이터
 */
export interface UpdateMemberData {
  /**
   * 닉네임
   */
  nickname?: string
  /**
   * 이메일
   */
  email?: string
}
