/* tslint:disable */
/* eslint-disable */
/**
 * care1-api 사용자 API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user'

/**
 *
 * @export
 * @interface UserSetting
 */
export interface UserSetting {
  /**
   * 마케팅 활용 동의 - 이메일
   * @type {boolean}
   * @memberof UserSetting
   */
  agreeEmail: boolean
  /**
   * 마케팅 활용 동의 - SMS
   * @type {boolean}
   * @memberof UserSetting
   */
  agreeSMS: boolean
  /**
   *
   * @type {number}
   * @memberof UserSetting
   */
  userId: number
  /**
   *
   * @type {User}
   * @memberof UserSetting
   */
  user: User
  /**
   *
   * @type {string}
   * @memberof UserSetting
   */
  updatedAt: string
}
