/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { AppleNotificationRequest } from '../models'
/**
 * AppleWebhookApi - axios parameter creator
 */
export const AppleWebhookApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Sign in with Apple 계정 변경 알림을 JSON 형식으로 처리합니다.
     * @summary Apple Server-to-Server 알림 수신 (JSON)
     * @param {string} signedPayload
     * @param {AppleNotificationRequest} appleNotificationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handleNotificationForm1: async (
      signedPayload: string,
      appleNotificationRequest: AppleNotificationRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'signedPayload' is not null or undefined
      assertParamExists('handleNotificationForm1', 'signedPayload', signedPayload)
      // verify required parameter 'appleNotificationRequest' is not null or undefined
      assertParamExists('handleNotificationForm1', 'appleNotificationRequest', appleNotificationRequest)
      const localVarPath = `/webhook/apple/notifications`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (signedPayload !== undefined) {
        localVarQueryParameter['signed_payload'] = signedPayload
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        appleNotificationRequest,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * AppleWebhookApi - functional programming interface
 */
export const AppleWebhookApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AppleWebhookApiAxiosParamCreator(configuration)
  return {
    /**
     * Sign in with Apple 계정 변경 알림을 JSON 형식으로 처리합니다.
     * @summary Apple Server-to-Server 알림 수신 (JSON)
     * @param {string} signedPayload
     * @param {AppleNotificationRequest} appleNotificationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async handleNotificationForm1(
      signedPayload: string,
      appleNotificationRequest: AppleNotificationRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.handleNotificationForm1(
        signedPayload,
        appleNotificationRequest,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AppleWebhookApi.handleNotificationForm1']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * AppleWebhookApi - factory interface
 */
export const AppleWebhookApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = AppleWebhookApiFp(configuration)
  return {
    /**
     * Sign in with Apple 계정 변경 알림을 JSON 형식으로 처리합니다.
     * @summary Apple Server-to-Server 알림 수신 (JSON)
     * @param {AppleWebhookApiHandleNotificationForm1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handleNotificationForm1(
      requestParameters: AppleWebhookApiHandleNotificationForm1Request,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<void> {
      return localVarFp
        .handleNotificationForm1(requestParameters.signedPayload, requestParameters.appleNotificationRequest, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for handleNotificationForm1 operation in AppleWebhookApi.
 */
export interface AppleWebhookApiHandleNotificationForm1Request {
  readonly signedPayload: string

  readonly appleNotificationRequest: AppleNotificationRequest
}

/**
 * AppleWebhookApi - object-oriented interface
 */
export class AppleWebhookApi extends BaseAPI {
  /**
   * Sign in with Apple 계정 변경 알림을 JSON 형식으로 처리합니다.
   * @summary Apple Server-to-Server 알림 수신 (JSON)
   * @param {AppleWebhookApiHandleNotificationForm1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public handleNotificationForm1(
    requestParameters: AppleWebhookApiHandleNotificationForm1Request,
    options?: RawAxiosRequestConfig
  ) {
    return AppleWebhookApiFp(this.configuration)
      .handleNotificationForm1(requestParameters.signedPayload, requestParameters.appleNotificationRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
