/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { BaseResponseBaseListResponseBookmarkDto } from '../models'
// @ts-ignore
import type { BaseResponseCreateBookmarkResponse } from '../models'
// @ts-ignore
import type { BaseResponseGetMessagesByBookmarkResponse } from '../models'
// @ts-ignore
import type { BaseResponseVoid } from '../models'
// @ts-ignore
import type { CreateBookmarkRequestDto } from '../models'
// @ts-ignore
import type { DeleteBookmarksRequestDto } from '../models'
// @ts-ignore
import type { Pageable } from '../models'
// @ts-ignore
import type { SwaggerErrorResponse } from '../models'
/**
 * BookmarksApi - axios parameter creator
 */
export const BookmarksApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 채팅 메시지를 북마크합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 생성
     * @param {number} chatRoomId
     * @param {CreateBookmarkRequestDto} createBookmarkRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBookmark: async (
      chatRoomId: number,
      createBookmarkRequestDto: CreateBookmarkRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'chatRoomId' is not null or undefined
      assertParamExists('createBookmark', 'chatRoomId', chatRoomId)
      // verify required parameter 'createBookmarkRequestDto' is not null or undefined
      assertParamExists('createBookmark', 'createBookmarkRequestDto', createBookmarkRequestDto)
      const localVarPath = `/chatrooms/{chatRoomId}/bookmarks`.replace(
        `{${'chatRoomId'}}`,
        encodeURIComponent(String(chatRoomId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        createBookmarkRequestDto,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 북마크를 삭제합니다 (소프트 삭제). JWT 토큰이 필요합니다.
     * @summary 북마크 삭제 (다건)
     * @param {number} chatRoomId
     * @param {DeleteBookmarksRequestDto} deleteBookmarksRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteBookmarks: async (
      chatRoomId: number,
      deleteBookmarksRequestDto: DeleteBookmarksRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'chatRoomId' is not null or undefined
      assertParamExists('deleteBookmarks', 'chatRoomId', chatRoomId)
      // verify required parameter 'deleteBookmarksRequestDto' is not null or undefined
      assertParamExists('deleteBookmarks', 'deleteBookmarksRequestDto', deleteBookmarksRequestDto)
      const localVarPath = `/chatrooms/{chatRoomId}/bookmarks`.replace(
        `{${'chatRoomId'}}`,
        encodeURIComponent(String(chatRoomId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        deleteBookmarksRequestDto,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 채팅방의 북마크 목록을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 리스트 조회
     * @param {number} chatRoomId
     * @param {Pageable} pageable
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBookmarkList: async (
      chatRoomId: number,
      pageable: Pageable,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'chatRoomId' is not null or undefined
      assertParamExists('getBookmarkList', 'chatRoomId', chatRoomId)
      // verify required parameter 'pageable' is not null or undefined
      assertParamExists('getBookmarkList', 'pageable', pageable)
      const localVarPath = `/chatrooms/{chatRoomId}/bookmarks`.replace(
        `{${'chatRoomId'}}`,
        encodeURIComponent(String(chatRoomId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (pageable !== undefined) {
        for (const [key, value] of Object.entries(pageable)) {
          localVarQueryParameter[key] = value
        }
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 북마크된 메시지 위치로 이동하기 위한 메시지 목록을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 기반 메시지 조회
     * @param {number} chatRoomId
     * @param {number} bookmarkId
     * @param {number} [size]
     * @param {string} [sort]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMessagesByBookmark: async (
      chatRoomId: number,
      bookmarkId: number,
      size?: number,
      sort?: string,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'chatRoomId' is not null or undefined
      assertParamExists('getMessagesByBookmark', 'chatRoomId', chatRoomId)
      // verify required parameter 'bookmarkId' is not null or undefined
      assertParamExists('getMessagesByBookmark', 'bookmarkId', bookmarkId)
      const localVarPath = `/chatrooms/{chatRoomId}/bookmarks/{bookmarkId}/messages`
        .replace(`{${'chatRoomId'}}`, encodeURIComponent(String(chatRoomId)))
        .replace(`{${'bookmarkId'}}`, encodeURIComponent(String(bookmarkId)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * BookmarksApi - functional programming interface
 */
export const BookmarksApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = BookmarksApiAxiosParamCreator(configuration)
  return {
    /**
     * 채팅 메시지를 북마크합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 생성
     * @param {number} chatRoomId
     * @param {CreateBookmarkRequestDto} createBookmarkRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createBookmark(
      chatRoomId: number,
      createBookmarkRequestDto: CreateBookmarkRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseCreateBookmarkResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createBookmark(
        chatRoomId,
        createBookmarkRequestDto,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['BookmarksApi.createBookmark']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 북마크를 삭제합니다 (소프트 삭제). JWT 토큰이 필요합니다.
     * @summary 북마크 삭제 (다건)
     * @param {number} chatRoomId
     * @param {DeleteBookmarksRequestDto} deleteBookmarksRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteBookmarks(
      chatRoomId: number,
      deleteBookmarksRequestDto: DeleteBookmarksRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseVoid>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBookmarks(
        chatRoomId,
        deleteBookmarksRequestDto,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['BookmarksApi.deleteBookmarks']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 채팅방의 북마크 목록을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 리스트 조회
     * @param {number} chatRoomId
     * @param {Pageable} pageable
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getBookmarkList(
      chatRoomId: number,
      pageable: Pageable,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBaseListResponseBookmarkDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getBookmarkList(chatRoomId, pageable, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['BookmarksApi.getBookmarkList']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 북마크된 메시지 위치로 이동하기 위한 메시지 목록을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 기반 메시지 조회
     * @param {number} chatRoomId
     * @param {number} bookmarkId
     * @param {number} [size]
     * @param {string} [sort]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getMessagesByBookmark(
      chatRoomId: number,
      bookmarkId: number,
      size?: number,
      sort?: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetMessagesByBookmarkResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getMessagesByBookmark(
        chatRoomId,
        bookmarkId,
        size,
        sort,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['BookmarksApi.getMessagesByBookmark']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * BookmarksApi - factory interface
 */
export const BookmarksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = BookmarksApiFp(configuration)
  return {
    /**
     * 채팅 메시지를 북마크합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 생성
     * @param {BookmarksApiCreateBookmarkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBookmark(
      requestParameters: BookmarksApiCreateBookmarkRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<BaseResponseCreateBookmarkResponse> {
      return localVarFp
        .createBookmark(requestParameters.chatRoomId, requestParameters.createBookmarkRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 북마크를 삭제합니다 (소프트 삭제). JWT 토큰이 필요합니다.
     * @summary 북마크 삭제 (다건)
     * @param {BookmarksApiDeleteBookmarksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteBookmarks(
      requestParameters: BookmarksApiDeleteBookmarksRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<BaseResponseVoid> {
      return localVarFp
        .deleteBookmarks(requestParameters.chatRoomId, requestParameters.deleteBookmarksRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 채팅방의 북마크 목록을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 리스트 조회
     * @param {BookmarksApiGetBookmarkListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBookmarkList(
      requestParameters: BookmarksApiGetBookmarkListRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<BaseResponseBaseListResponseBookmarkDto> {
      return localVarFp
        .getBookmarkList(requestParameters.chatRoomId, requestParameters.pageable, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 북마크된 메시지 위치로 이동하기 위한 메시지 목록을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 북마크 기반 메시지 조회
     * @param {BookmarksApiGetMessagesByBookmarkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMessagesByBookmark(
      requestParameters: BookmarksApiGetMessagesByBookmarkRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<BaseResponseGetMessagesByBookmarkResponse> {
      return localVarFp
        .getMessagesByBookmark(
          requestParameters.chatRoomId,
          requestParameters.bookmarkId,
          requestParameters.size,
          requestParameters.sort,
          options
        )
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for createBookmark operation in BookmarksApi.
 */
export interface BookmarksApiCreateBookmarkRequest {
  readonly chatRoomId: number

  readonly createBookmarkRequestDto: CreateBookmarkRequestDto
}

/**
 * Request parameters for deleteBookmarks operation in BookmarksApi.
 */
export interface BookmarksApiDeleteBookmarksRequest {
  readonly chatRoomId: number

  readonly deleteBookmarksRequestDto: DeleteBookmarksRequestDto
}

/**
 * Request parameters for getBookmarkList operation in BookmarksApi.
 */
export interface BookmarksApiGetBookmarkListRequest {
  readonly chatRoomId: number

  readonly pageable: Pageable
}

/**
 * Request parameters for getMessagesByBookmark operation in BookmarksApi.
 */
export interface BookmarksApiGetMessagesByBookmarkRequest {
  readonly chatRoomId: number

  readonly bookmarkId: number

  readonly size?: number

  readonly sort?: string
}

/**
 * BookmarksApi - object-oriented interface
 */
export class BookmarksApi extends BaseAPI {
  /**
   * 채팅 메시지를 북마크합니다. JWT 토큰이 필요합니다.
   * @summary 북마크 생성
   * @param {BookmarksApiCreateBookmarkRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public createBookmark(requestParameters: BookmarksApiCreateBookmarkRequest, options?: RawAxiosRequestConfig) {
    return BookmarksApiFp(this.configuration)
      .createBookmark(requestParameters.chatRoomId, requestParameters.createBookmarkRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 북마크를 삭제합니다 (소프트 삭제). JWT 토큰이 필요합니다.
   * @summary 북마크 삭제 (다건)
   * @param {BookmarksApiDeleteBookmarksRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public deleteBookmarks(requestParameters: BookmarksApiDeleteBookmarksRequest, options?: RawAxiosRequestConfig) {
    return BookmarksApiFp(this.configuration)
      .deleteBookmarks(requestParameters.chatRoomId, requestParameters.deleteBookmarksRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 채팅방의 북마크 목록을 조회합니다. JWT 토큰이 필요합니다.
   * @summary 북마크 리스트 조회
   * @param {BookmarksApiGetBookmarkListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getBookmarkList(requestParameters: BookmarksApiGetBookmarkListRequest, options?: RawAxiosRequestConfig) {
    return BookmarksApiFp(this.configuration)
      .getBookmarkList(requestParameters.chatRoomId, requestParameters.pageable, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 북마크된 메시지 위치로 이동하기 위한 메시지 목록을 조회합니다. JWT 토큰이 필요합니다.
   * @summary 북마크 기반 메시지 조회
   * @param {BookmarksApiGetMessagesByBookmarkRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getMessagesByBookmark(
    requestParameters: BookmarksApiGetMessagesByBookmarkRequest,
    options?: RawAxiosRequestConfig
  ) {
    return BookmarksApiFp(this.configuration)
      .getMessagesByBookmark(
        requestParameters.chatRoomId,
        requestParameters.bookmarkId,
        requestParameters.size,
        requestParameters.sort,
        options
      )
      .then((request) => request(this.axios, this.basePath))
  }
}
