/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { CoupleLinkRequestDto } from '../models'
// @ts-ignore
import type { CoupleLinkSuccessResponse } from '../models'
// @ts-ignore
import type { CoupleUnlinkSuccessResponse } from '../models'
// @ts-ignore
import type { SwaggerErrorResponse } from '../models'
/**
 * CouplesApi - axios parameter creator
 */
export const CouplesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 커플 초대코드를 사용하여 커플을 연결합니다. JWT 토큰이 필요합니다.
     * @summary 커플 연결
     * @param {CoupleLinkRequestDto} coupleLinkRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    linkCouple: async (
      coupleLinkRequestDto: CoupleLinkRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'coupleLinkRequestDto' is not null or undefined
      assertParamExists('linkCouple', 'coupleLinkRequestDto', coupleLinkRequestDto)
      const localVarPath = `/couples`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(coupleLinkRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 연결된 커플을 끊습니다. JWT 토큰이 필요합니다.
     * @summary 커플 연결 끊기
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlinkCouple: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/couples`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * CouplesApi - functional programming interface
 */
export const CouplesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = CouplesApiAxiosParamCreator(configuration)
  return {
    /**
     * 커플 초대코드를 사용하여 커플을 연결합니다. JWT 토큰이 필요합니다.
     * @summary 커플 연결
     * @param {CoupleLinkRequestDto} coupleLinkRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async linkCouple(
      coupleLinkRequestDto: CoupleLinkRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoupleLinkSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.linkCouple(coupleLinkRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['CouplesApi.linkCouple']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 연결된 커플을 끊습니다. JWT 토큰이 필요합니다.
     * @summary 커플 연결 끊기
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async unlinkCouple(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CoupleUnlinkSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.unlinkCouple(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['CouplesApi.unlinkCouple']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * CouplesApi - factory interface
 */
export const CouplesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = CouplesApiFp(configuration)
  return {
    /**
     * 커플 초대코드를 사용하여 커플을 연결합니다. JWT 토큰이 필요합니다.
     * @summary 커플 연결
     * @param {CouplesApiLinkCoupleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    linkCouple(
      requestParameters: CouplesApiLinkCoupleRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<CoupleLinkSuccessResponse> {
      return localVarFp
        .linkCouple(requestParameters.coupleLinkRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 연결된 커플을 끊습니다. JWT 토큰이 필요합니다.
     * @summary 커플 연결 끊기
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlinkCouple(options?: RawAxiosRequestConfig): AxiosPromise<CoupleUnlinkSuccessResponse> {
      return localVarFp.unlinkCouple(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for linkCouple operation in CouplesApi.
 */
export interface CouplesApiLinkCoupleRequest {
  readonly coupleLinkRequestDto: CoupleLinkRequestDto
}

/**
 * CouplesApi - object-oriented interface
 */
export class CouplesApi extends BaseAPI {
  /**
   * 커플 초대코드를 사용하여 커플을 연결합니다. JWT 토큰이 필요합니다.
   * @summary 커플 연결
   * @param {CouplesApiLinkCoupleRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public linkCouple(requestParameters: CouplesApiLinkCoupleRequest, options?: RawAxiosRequestConfig) {
    return CouplesApiFp(this.configuration)
      .linkCouple(requestParameters.coupleLinkRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 연결된 커플을 끊습니다. JWT 토큰이 필요합니다.
   * @summary 커플 연결 끊기
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public unlinkCouple(options?: RawAxiosRequestConfig) {
    return CouplesApiFp(this.configuration)
      .unlinkCouple(options)
      .then((request) => request(this.axios, this.basePath))
  }
}
