/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { AnswerRequestDto } from '../models'
// @ts-ignore
import type { AnswerSuccessResponse } from '../models'
// @ts-ignore
import type { PastAnswerSuccessResponse } from '../models'
// @ts-ignore
import type { PastQuestionSuccessResponse } from '../models'
// @ts-ignore
import type { QuestionListSuccessResponse } from '../models'
// @ts-ignore
import type { QuestionSuccessResponse } from '../models'
// @ts-ignore
import type { SwaggerErrorResponse } from '../models'
/**
 * QuestionsApi - axios parameter creator
 * @export
 */
export const QuestionsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 커플 과거 질문 답변을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 질문 답변 조회
     * @param {string} coupleQuestionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAnswer: async (coupleQuestionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'coupleQuestionId' is not null or undefined
      assertParamExists('getAnswer', 'coupleQuestionId', coupleQuestionId)
      const localVarPath = `/questions/answers/{coupleQuestionId}`.replace(
        `{${'coupleQuestionId'}}`,
        encodeURIComponent(String(coupleQuestionId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 질문 내용 조회
     * @param {string} coupleQuestionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getQuestion: async (coupleQuestionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'coupleQuestionId' is not null or undefined
      assertParamExists('getQuestion', 'coupleQuestionId', coupleQuestionId)
      const localVarPath = `/questions/{coupleQuestionId}`.replace(
        `{${'coupleQuestionId'}}`,
        encodeURIComponent(String(coupleQuestionId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 여태까지 등록된 커플 오늘의 질문 리스트를 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 리스트 조회
     * @param {number} [page]
     * @param {number} [size]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getQuestionList: async (
      page?: number,
      size?: number,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/questions`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTodayQuestion: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/questions/today`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 커플 오늘의 질문에 답변을 등록합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 답변 등록
     * @param {number} coupleQuestionId
     * @param {AnswerRequestDto} answerRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postAnswer: async (
      coupleQuestionId: number,
      answerRequestDto: AnswerRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'coupleQuestionId' is not null or undefined
      assertParamExists('postAnswer', 'coupleQuestionId', coupleQuestionId)
      // verify required parameter 'answerRequestDto' is not null or undefined
      assertParamExists('postAnswer', 'answerRequestDto', answerRequestDto)
      const localVarPath = `/questions/answers/{coupleQuestionId}`.replace(
        `{${'coupleQuestionId'}}`,
        encodeURIComponent(String(coupleQuestionId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(answerRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * QuestionsApi - functional programming interface
 * @export
 */
export const QuestionsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = QuestionsApiAxiosParamCreator(configuration)
  return {
    /**
     * 커플 과거 질문 답변을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 질문 답변 조회
     * @param {string} coupleQuestionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAnswer(
      coupleQuestionId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PastAnswerSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAnswer(coupleQuestionId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['QuestionsApi.getAnswer']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 질문 내용 조회
     * @param {string} coupleQuestionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getQuestion(
      coupleQuestionId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PastQuestionSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestion(coupleQuestionId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['QuestionsApi.getQuestion']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 여태까지 등록된 커플 오늘의 질문 리스트를 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 리스트 조회
     * @param {number} [page]
     * @param {number} [size]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getQuestionList(
      page?: number,
      size?: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionListSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getQuestionList(page, size, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['QuestionsApi.getQuestionList']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTodayQuestion(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuestionSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTodayQuestion(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['QuestionsApi.getTodayQuestion']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 커플 오늘의 질문에 답변을 등록합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 답변 등록
     * @param {number} coupleQuestionId
     * @param {AnswerRequestDto} answerRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async postAnswer(
      coupleQuestionId: number,
      answerRequestDto: AnswerRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AnswerSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.postAnswer(coupleQuestionId, answerRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['QuestionsApi.postAnswer']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * QuestionsApi - factory interface
 * @export
 */
export const QuestionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = QuestionsApiFp(configuration)
  return {
    /**
     * 커플 과거 질문 답변을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 질문 답변 조회
     * @param {QuestionsApiGetAnswerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAnswer(
      requestParameters: QuestionsApiGetAnswerRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<PastAnswerSuccessResponse> {
      return localVarFp
        .getAnswer(requestParameters.coupleQuestionId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 질문 내용 조회
     * @param {QuestionsApiGetQuestionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getQuestion(
      requestParameters: QuestionsApiGetQuestionRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<PastQuestionSuccessResponse> {
      return localVarFp
        .getQuestion(requestParameters.coupleQuestionId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 여태까지 등록된 커플 오늘의 질문 리스트를 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 리스트 조회
     * @param {QuestionsApiGetQuestionListRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getQuestionList(
      requestParameters: QuestionsApiGetQuestionListRequest = {},
      options?: RawAxiosRequestConfig
    ): AxiosPromise<QuestionListSuccessResponse> {
      return localVarFp
        .getQuestionList(requestParameters.page, requestParameters.size, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTodayQuestion(options?: RawAxiosRequestConfig): AxiosPromise<QuestionSuccessResponse> {
      return localVarFp.getTodayQuestion(options).then((request) => request(axios, basePath))
    },
    /**
     * 커플 오늘의 질문에 답변을 등록합니다. JWT 토큰이 필요합니다.
     * @summary 🚧 [개발 전] 오늘의 질문 답변 등록
     * @param {QuestionsApiPostAnswerRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postAnswer(
      requestParameters: QuestionsApiPostAnswerRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<AnswerSuccessResponse> {
      return localVarFp
        .postAnswer(requestParameters.coupleQuestionId, requestParameters.answerRequestDto, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for getAnswer operation in QuestionsApi.
 * @export
 * @interface QuestionsApiGetAnswerRequest
 */
export interface QuestionsApiGetAnswerRequest {
  /**
   *
   * @type {string}
   * @memberof QuestionsApiGetAnswer
   */
  readonly coupleQuestionId: string
}

/**
 * Request parameters for getQuestion operation in QuestionsApi.
 * @export
 * @interface QuestionsApiGetQuestionRequest
 */
export interface QuestionsApiGetQuestionRequest {
  /**
   *
   * @type {string}
   * @memberof QuestionsApiGetQuestion
   */
  readonly coupleQuestionId: string
}

/**
 * Request parameters for getQuestionList operation in QuestionsApi.
 * @export
 * @interface QuestionsApiGetQuestionListRequest
 */
export interface QuestionsApiGetQuestionListRequest {
  /**
   *
   * @type {number}
   * @memberof QuestionsApiGetQuestionList
   */
  readonly page?: number

  /**
   *
   * @type {number}
   * @memberof QuestionsApiGetQuestionList
   */
  readonly size?: number
}

/**
 * Request parameters for postAnswer operation in QuestionsApi.
 * @export
 * @interface QuestionsApiPostAnswerRequest
 */
export interface QuestionsApiPostAnswerRequest {
  /**
   *
   * @type {number}
   * @memberof QuestionsApiPostAnswer
   */
  readonly coupleQuestionId: number

  /**
   *
   * @type {AnswerRequestDto}
   * @memberof QuestionsApiPostAnswer
   */
  readonly answerRequestDto: AnswerRequestDto
}

/**
 * QuestionsApi - object-oriented interface
 * @export
 * @class QuestionsApi
 * @extends {BaseAPI}
 */
export class QuestionsApi extends BaseAPI {
  /**
   * 커플 과거 질문 답변을 조회합니다. JWT 토큰이 필요합니다.
   * @summary 🚧 [개발 전] 질문 답변 조회
   * @param {QuestionsApiGetAnswerRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof QuestionsApi
   */
  public getAnswer(requestParameters: QuestionsApiGetAnswerRequest, options?: RawAxiosRequestConfig) {
    return QuestionsApiFp(this.configuration)
      .getAnswer(requestParameters.coupleQuestionId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
   * @summary 🚧 [개발 전] 질문 내용 조회
   * @param {QuestionsApiGetQuestionRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof QuestionsApi
   */
  public getQuestion(requestParameters: QuestionsApiGetQuestionRequest, options?: RawAxiosRequestConfig) {
    return QuestionsApiFp(this.configuration)
      .getQuestion(requestParameters.coupleQuestionId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 여태까지 등록된 커플 오늘의 질문 리스트를 조회합니다. JWT 토큰이 필요합니다.
   * @summary 🚧 [개발 전] 오늘의 질문 리스트 조회
   * @param {QuestionsApiGetQuestionListRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof QuestionsApi
   */
  public getQuestionList(requestParameters: QuestionsApiGetQuestionListRequest = {}, options?: RawAxiosRequestConfig) {
    return QuestionsApiFp(this.configuration)
      .getQuestionList(requestParameters.page, requestParameters.size, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 커플 오늘의 질문을 조회합니다. JWT 토큰이 필요합니다.
   * @summary 🚧 [개발 전] 오늘의 질문 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof QuestionsApi
   */
  public getTodayQuestion(options?: RawAxiosRequestConfig) {
    return QuestionsApiFp(this.configuration)
      .getTodayQuestion(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 커플 오늘의 질문에 답변을 등록합니다. JWT 토큰이 필요합니다.
   * @summary 🚧 [개발 전] 오늘의 질문 답변 등록
   * @param {QuestionsApiPostAnswerRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof QuestionsApi
   */
  public postAnswer(requestParameters: QuestionsApiPostAnswerRequest, options?: RawAxiosRequestConfig) {
    return QuestionsApiFp(this.configuration)
      .postAnswer(requestParameters.coupleQuestionId, requestParameters.answerRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
