/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { SwaggerErrorResponse } from '../models'
/**
 * SSEConnectionAPIApi - axios parameter creator
 * @export
 */
export const SSEConnectionAPIApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 사용자의 SSE 연결을 설정합니다. JWT 토큰이 필요합니다. BaseResponse를 사용하지 않습니다.
     * @summary SSE 연결
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    connectSse: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/sse/connect`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * SSEConnectionAPIApi - functional programming interface
 * @export
 */
export const SSEConnectionAPIApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = SSEConnectionAPIApiAxiosParamCreator(configuration)
  return {
    /**
     * 사용자의 SSE 연결을 설정합니다. JWT 토큰이 필요합니다. BaseResponse를 사용하지 않습니다.
     * @summary SSE 연결
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async connectSse(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.connectSse(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['SSEConnectionAPIApi.connectSse']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * SSEConnectionAPIApi - factory interface
 * @export
 */
export const SSEConnectionAPIApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = SSEConnectionAPIApiFp(configuration)
  return {
    /**
     * 사용자의 SSE 연결을 설정합니다. JWT 토큰이 필요합니다. BaseResponse를 사용하지 않습니다.
     * @summary SSE 연결
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    connectSse(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp.connectSse(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * SSEConnectionAPIApi - object-oriented interface
 * @export
 * @class SSEConnectionAPIApi
 * @extends {BaseAPI}
 */
export class SSEConnectionAPIApi extends BaseAPI {
  /**
   * 사용자의 SSE 연결을 설정합니다. JWT 토큰이 필요합니다. BaseResponse를 사용하지 않습니다.
   * @summary SSE 연결
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SSEConnectionAPIApi
   */
  public connectSse(options?: RawAxiosRequestConfig) {
    return SSEConnectionAPIApiFp(this.configuration)
      .connectSse(options)
      .then((request) => request(this.axios, this.basePath))
  }
}
