/* tslint:disable */
/* eslint-disable */
/**
 * Malmo API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { TermsListSuccessResponse } from '../models'
/**
 * TermsApi - axios parameter creator
 */
export const TermsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 서비스 이용약관 목록을 조회합니다. 회원가입 시 동의가 필요한 약관들이 포함됩니다.
     * @summary 약관 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTerms: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/terms`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Authentication required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * TermsApi - functional programming interface
 */
export const TermsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TermsApiAxiosParamCreator(configuration)
  return {
    /**
     * 서비스 이용약관 목록을 조회합니다. 회원가입 시 동의가 필요한 약관들이 포함됩니다.
     * @summary 약관 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTerms(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TermsListSuccessResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTerms(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TermsApi.getTerms']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * TermsApi - factory interface
 */
export const TermsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = TermsApiFp(configuration)
  return {
    /**
     * 서비스 이용약관 목록을 조회합니다. 회원가입 시 동의가 필요한 약관들이 포함됩니다.
     * @summary 약관 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTerms(options?: RawAxiosRequestConfig): AxiosPromise<TermsListSuccessResponse> {
      return localVarFp.getTerms(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * TermsApi - object-oriented interface
 */
export class TermsApi extends BaseAPI {
  /**
   * 서비스 이용약관 목록을 조회합니다. 회원가입 시 동의가 필요한 약관들이 포함됩니다.
   * @summary 약관 목록 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  public getTerms(options?: RawAxiosRequestConfig) {
    return TermsApiFp(this.configuration)
      .getTerms(options)
      .then((request) => request(this.axios, this.basePath))
  }
}
