/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as OnboardingLayoutImport } from './app/onboarding/layout'
import { Route as ChatLayoutImport } from './app/chat/layout'
import { Route as PageImport } from './app/page'
import { Route as TutorialPageImport } from './app/tutorial/page'
import { Route as RelationshipStatusPageImport } from './app/relationship-status/page'
import { Route as PersonalityFlowLoadingPageImport } from './app/personality-flow-loading/page'
import { Route as PartnerStatusPageImport } from './app/partner-status/page'
import { Route as PartnerResultPreviewPageImport } from './app/partner-result-preview/page'
import { Route as PartnerMbtiPageImport } from './app/partner-mbti/page'
import { Route as PartnerAttachmentSelectPageImport } from './app/partner-attachment-select/page'
import { Route as MyResultPreviewPageImport } from './app/my-result-preview/page'
import { Route as MyPagePageImport } from './app/my-page/page'
import { Route as MyAttachmentSelectPageImport } from './app/my-attachment-select/page'
import { Route as MbtiPageImport } from './app/mbti/page'
import { Route as LoginPageImport } from './app/login/page'
import { Route as IntroPageImport } from './app/intro/page'
import { Route as HistoryPageImport } from './app/history/page'
import { Route as ChatPageImport } from './app/chat/page'
import { Route as AttachmentTestPageImport } from './app/attachment-test/page'
import { Route as TermsPrivacyPolicyPageImport } from './app/terms/privacy-policy/page'
import { Route as OnboardingTermsPageImport } from './app/onboarding/terms/page'
import { Route as OnboardingRelationshipStatusPageImport } from './app/onboarding/relationship-status/page'
import { Route as OnboardingNicknamePageImport } from './app/onboarding/nickname/page'
import { Route as MyPageProfilePageImport } from './app/my-page/profile/page'
import { Route as MyPageAccountSettingsPageImport } from './app/my-page/account-settings/page'
import { Route as HistoryDeletePageImport } from './app/history/delete/page'
import { Route as ChatResultPageImport } from './app/chat/result/page'
import { Route as ChatLoadingPageImport } from './app/chat/loading/page'
import { Route as AttachmentTestQuestionPageImport } from './app/attachment-test/question/page'
import { Route as AttachmentTestResultPartnerPageImport } from './app/attachment-test/result/partner/page'
import { Route as AttachmentTestResultMyPageImport } from './app/attachment-test/result/my/page'

// Create/Update Routes

const OnboardingLayoutRoute = OnboardingLayoutImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const ChatLayoutRoute = ChatLayoutImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TutorialPageRoute = TutorialPageImport.update({
  id: '/tutorial/',
  path: '/tutorial/',
  getParentRoute: () => rootRoute,
} as any)

const RelationshipStatusPageRoute = RelationshipStatusPageImport.update({
  id: '/relationship-status/',
  path: '/relationship-status/',
  getParentRoute: () => rootRoute,
} as any)

const PersonalityFlowLoadingPageRoute = PersonalityFlowLoadingPageImport.update({
  id: '/personality-flow-loading/',
  path: '/personality-flow-loading/',
  getParentRoute: () => rootRoute,
} as any)

const PartnerStatusPageRoute = PartnerStatusPageImport.update({
  id: '/partner-status/',
  path: '/partner-status/',
  getParentRoute: () => rootRoute,
} as any)

const PartnerResultPreviewPageRoute = PartnerResultPreviewPageImport.update({
  id: '/partner-result-preview/',
  path: '/partner-result-preview/',
  getParentRoute: () => rootRoute,
} as any)

const PartnerMbtiPageRoute = PartnerMbtiPageImport.update({
  id: '/partner-mbti/',
  path: '/partner-mbti/',
  getParentRoute: () => rootRoute,
} as any)

const PartnerAttachmentSelectPageRoute = PartnerAttachmentSelectPageImport.update({
  id: '/partner-attachment-select/',
  path: '/partner-attachment-select/',
  getParentRoute: () => rootRoute,
} as any)

const MyResultPreviewPageRoute = MyResultPreviewPageImport.update({
  id: '/my-result-preview/',
  path: '/my-result-preview/',
  getParentRoute: () => rootRoute,
} as any)

const MyPagePageRoute = MyPagePageImport.update({
  id: '/my-page/',
  path: '/my-page/',
  getParentRoute: () => rootRoute,
} as any)

const MyAttachmentSelectPageRoute = MyAttachmentSelectPageImport.update({
  id: '/my-attachment-select/',
  path: '/my-attachment-select/',
  getParentRoute: () => rootRoute,
} as any)

const MbtiPageRoute = MbtiPageImport.update({
  id: '/mbti/',
  path: '/mbti/',
  getParentRoute: () => rootRoute,
} as any)

const LoginPageRoute = LoginPageImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const IntroPageRoute = IntroPageImport.update({
  id: '/intro/',
  path: '/intro/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryPageRoute = HistoryPageImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const ChatPageRoute = ChatPageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const AttachmentTestPageRoute = AttachmentTestPageImport.update({
  id: '/attachment-test/',
  path: '/attachment-test/',
  getParentRoute: () => rootRoute,
} as any)

const TermsPrivacyPolicyPageRoute = TermsPrivacyPolicyPageImport.update({
  id: '/terms/privacy-policy/',
  path: '/terms/privacy-policy/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingTermsPageRoute = OnboardingTermsPageImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingRelationshipStatusPageRoute = OnboardingRelationshipStatusPageImport.update({
  id: '/relationship-status/',
  path: '/relationship-status/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingNicknamePageRoute = OnboardingNicknamePageImport.update({
  id: '/nickname/',
  path: '/nickname/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const MyPageProfilePageRoute = MyPageProfilePageImport.update({
  id: '/my-page/profile/',
  path: '/my-page/profile/',
  getParentRoute: () => rootRoute,
} as any)

const MyPageAccountSettingsPageRoute = MyPageAccountSettingsPageImport.update({
  id: '/my-page/account-settings/',
  path: '/my-page/account-settings/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryDeletePageRoute = HistoryDeletePageImport.update({
  id: '/history/delete/',
  path: '/history/delete/',
  getParentRoute: () => rootRoute,
} as any)

const ChatResultPageRoute = ChatResultPageImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const ChatLoadingPageRoute = ChatLoadingPageImport.update({
  id: '/loading/',
  path: '/loading/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const AttachmentTestQuestionPageRoute = AttachmentTestQuestionPageImport.update({
  id: '/attachment-test/question/',
  path: '/attachment-test/question/',
  getParentRoute: () => rootRoute,
} as any)

const AttachmentTestResultPartnerPageRoute = AttachmentTestResultPartnerPageImport.update({
  id: '/attachment-test/result/partner/',
  path: '/attachment-test/result/partner/',
  getParentRoute: () => rootRoute,
} as any)

const AttachmentTestResultMyPageRoute = AttachmentTestResultMyPageImport.update({
  id: '/attachment-test/result/my/',
  path: '/attachment-test/result/my/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatLayoutImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/attachment-test/': {
      id: '/attachment-test/'
      path: '/attachment-test'
      fullPath: '/attachment-test'
      preLoaderRoute: typeof AttachmentTestPageImport
      parentRoute: typeof rootRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatPageImport
      parentRoute: typeof ChatLayoutImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryPageImport
      parentRoute: typeof rootRoute
    }
    '/intro/': {
      id: '/intro/'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroPageImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginPageImport
      parentRoute: typeof rootRoute
    }
    '/mbti/': {
      id: '/mbti/'
      path: '/mbti'
      fullPath: '/mbti'
      preLoaderRoute: typeof MbtiPageImport
      parentRoute: typeof rootRoute
    }
    '/my-attachment-select/': {
      id: '/my-attachment-select/'
      path: '/my-attachment-select'
      fullPath: '/my-attachment-select'
      preLoaderRoute: typeof MyAttachmentSelectPageImport
      parentRoute: typeof rootRoute
    }
    '/my-page/': {
      id: '/my-page/'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPagePageImport
      parentRoute: typeof rootRoute
    }
    '/my-result-preview/': {
      id: '/my-result-preview/'
      path: '/my-result-preview'
      fullPath: '/my-result-preview'
      preLoaderRoute: typeof MyResultPreviewPageImport
      parentRoute: typeof rootRoute
    }
    '/partner-attachment-select/': {
      id: '/partner-attachment-select/'
      path: '/partner-attachment-select'
      fullPath: '/partner-attachment-select'
      preLoaderRoute: typeof PartnerAttachmentSelectPageImport
      parentRoute: typeof rootRoute
    }
    '/partner-mbti/': {
      id: '/partner-mbti/'
      path: '/partner-mbti'
      fullPath: '/partner-mbti'
      preLoaderRoute: typeof PartnerMbtiPageImport
      parentRoute: typeof rootRoute
    }
    '/partner-result-preview/': {
      id: '/partner-result-preview/'
      path: '/partner-result-preview'
      fullPath: '/partner-result-preview'
      preLoaderRoute: typeof PartnerResultPreviewPageImport
      parentRoute: typeof rootRoute
    }
    '/partner-status/': {
      id: '/partner-status/'
      path: '/partner-status'
      fullPath: '/partner-status'
      preLoaderRoute: typeof PartnerStatusPageImport
      parentRoute: typeof rootRoute
    }
    '/personality-flow-loading/': {
      id: '/personality-flow-loading/'
      path: '/personality-flow-loading'
      fullPath: '/personality-flow-loading'
      preLoaderRoute: typeof PersonalityFlowLoadingPageImport
      parentRoute: typeof rootRoute
    }
    '/relationship-status/': {
      id: '/relationship-status/'
      path: '/relationship-status'
      fullPath: '/relationship-status'
      preLoaderRoute: typeof RelationshipStatusPageImport
      parentRoute: typeof rootRoute
    }
    '/tutorial/': {
      id: '/tutorial/'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialPageImport
      parentRoute: typeof rootRoute
    }
    '/attachment-test/question/': {
      id: '/attachment-test/question/'
      path: '/attachment-test/question'
      fullPath: '/attachment-test/question'
      preLoaderRoute: typeof AttachmentTestQuestionPageImport
      parentRoute: typeof rootRoute
    }
    '/chat/loading/': {
      id: '/chat/loading/'
      path: '/loading'
      fullPath: '/chat/loading'
      preLoaderRoute: typeof ChatLoadingPageImport
      parentRoute: typeof ChatLayoutImport
    }
    '/chat/result/': {
      id: '/chat/result/'
      path: '/result'
      fullPath: '/chat/result'
      preLoaderRoute: typeof ChatResultPageImport
      parentRoute: typeof ChatLayoutImport
    }
    '/history/delete/': {
      id: '/history/delete/'
      path: '/history/delete'
      fullPath: '/history/delete'
      preLoaderRoute: typeof HistoryDeletePageImport
      parentRoute: typeof rootRoute
    }
    '/my-page/account-settings/': {
      id: '/my-page/account-settings/'
      path: '/my-page/account-settings'
      fullPath: '/my-page/account-settings'
      preLoaderRoute: typeof MyPageAccountSettingsPageImport
      parentRoute: typeof rootRoute
    }
    '/my-page/profile/': {
      id: '/my-page/profile/'
      path: '/my-page/profile'
      fullPath: '/my-page/profile'
      preLoaderRoute: typeof MyPageProfilePageImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/nickname/': {
      id: '/onboarding/nickname/'
      path: '/nickname'
      fullPath: '/onboarding/nickname'
      preLoaderRoute: typeof OnboardingNicknamePageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/relationship-status/': {
      id: '/onboarding/relationship-status/'
      path: '/relationship-status'
      fullPath: '/onboarding/relationship-status'
      preLoaderRoute: typeof OnboardingRelationshipStatusPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/terms/': {
      id: '/onboarding/terms/'
      path: '/terms'
      fullPath: '/onboarding/terms'
      preLoaderRoute: typeof OnboardingTermsPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/terms/privacy-policy/': {
      id: '/terms/privacy-policy/'
      path: '/terms/privacy-policy'
      fullPath: '/terms/privacy-policy'
      preLoaderRoute: typeof TermsPrivacyPolicyPageImport
      parentRoute: typeof rootRoute
    }
    '/attachment-test/result/my/': {
      id: '/attachment-test/result/my/'
      path: '/attachment-test/result/my'
      fullPath: '/attachment-test/result/my'
      preLoaderRoute: typeof AttachmentTestResultMyPageImport
      parentRoute: typeof rootRoute
    }
    '/attachment-test/result/partner/': {
      id: '/attachment-test/result/partner/'
      path: '/attachment-test/result/partner'
      fullPath: '/attachment-test/result/partner'
      preLoaderRoute: typeof AttachmentTestResultPartnerPageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ChatLayoutRouteChildren {
  ChatPageRoute: typeof ChatPageRoute
  ChatLoadingPageRoute: typeof ChatLoadingPageRoute
  ChatResultPageRoute: typeof ChatResultPageRoute
}

const ChatLayoutRouteChildren: ChatLayoutRouteChildren = {
  ChatPageRoute: ChatPageRoute,
  ChatLoadingPageRoute: ChatLoadingPageRoute,
  ChatResultPageRoute: ChatResultPageRoute,
}

const ChatLayoutRouteWithChildren = ChatLayoutRoute._addFileChildren(ChatLayoutRouteChildren)

interface OnboardingLayoutRouteChildren {
  OnboardingNicknamePageRoute: typeof OnboardingNicknamePageRoute
  OnboardingRelationshipStatusPageRoute: typeof OnboardingRelationshipStatusPageRoute
  OnboardingTermsPageRoute: typeof OnboardingTermsPageRoute
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingNicknamePageRoute: OnboardingNicknamePageRoute,
  OnboardingRelationshipStatusPageRoute: OnboardingRelationshipStatusPageRoute,
  OnboardingTermsPageRoute: OnboardingTermsPageRoute,
}

const OnboardingLayoutRouteWithChildren = OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/chat': typeof ChatLayoutRouteWithChildren
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/attachment-test': typeof AttachmentTestPageRoute
  '/chat/': typeof ChatPageRoute
  '/history': typeof HistoryPageRoute
  '/intro': typeof IntroPageRoute
  '/login': typeof LoginPageRoute
  '/mbti': typeof MbtiPageRoute
  '/my-attachment-select': typeof MyAttachmentSelectPageRoute
  '/my-page': typeof MyPagePageRoute
  '/my-result-preview': typeof MyResultPreviewPageRoute
  '/partner-attachment-select': typeof PartnerAttachmentSelectPageRoute
  '/partner-mbti': typeof PartnerMbtiPageRoute
  '/partner-result-preview': typeof PartnerResultPreviewPageRoute
  '/partner-status': typeof PartnerStatusPageRoute
  '/personality-flow-loading': typeof PersonalityFlowLoadingPageRoute
  '/relationship-status': typeof RelationshipStatusPageRoute
  '/tutorial': typeof TutorialPageRoute
  '/attachment-test/question': typeof AttachmentTestQuestionPageRoute
  '/chat/loading': typeof ChatLoadingPageRoute
  '/chat/result': typeof ChatResultPageRoute
  '/history/delete': typeof HistoryDeletePageRoute
  '/my-page/account-settings': typeof MyPageAccountSettingsPageRoute
  '/my-page/profile': typeof MyPageProfilePageRoute
  '/onboarding/nickname': typeof OnboardingNicknamePageRoute
  '/onboarding/relationship-status': typeof OnboardingRelationshipStatusPageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/terms/privacy-policy': typeof TermsPrivacyPolicyPageRoute
  '/attachment-test/result/my': typeof AttachmentTestResultMyPageRoute
  '/attachment-test/result/partner': typeof AttachmentTestResultPartnerPageRoute
}

export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/attachment-test': typeof AttachmentTestPageRoute
  '/chat': typeof ChatPageRoute
  '/history': typeof HistoryPageRoute
  '/intro': typeof IntroPageRoute
  '/login': typeof LoginPageRoute
  '/mbti': typeof MbtiPageRoute
  '/my-attachment-select': typeof MyAttachmentSelectPageRoute
  '/my-page': typeof MyPagePageRoute
  '/my-result-preview': typeof MyResultPreviewPageRoute
  '/partner-attachment-select': typeof PartnerAttachmentSelectPageRoute
  '/partner-mbti': typeof PartnerMbtiPageRoute
  '/partner-result-preview': typeof PartnerResultPreviewPageRoute
  '/partner-status': typeof PartnerStatusPageRoute
  '/personality-flow-loading': typeof PersonalityFlowLoadingPageRoute
  '/relationship-status': typeof RelationshipStatusPageRoute
  '/tutorial': typeof TutorialPageRoute
  '/attachment-test/question': typeof AttachmentTestQuestionPageRoute
  '/chat/loading': typeof ChatLoadingPageRoute
  '/chat/result': typeof ChatResultPageRoute
  '/history/delete': typeof HistoryDeletePageRoute
  '/my-page/account-settings': typeof MyPageAccountSettingsPageRoute
  '/my-page/profile': typeof MyPageProfilePageRoute
  '/onboarding/nickname': typeof OnboardingNicknamePageRoute
  '/onboarding/relationship-status': typeof OnboardingRelationshipStatusPageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/terms/privacy-policy': typeof TermsPrivacyPolicyPageRoute
  '/attachment-test/result/my': typeof AttachmentTestResultMyPageRoute
  '/attachment-test/result/partner': typeof AttachmentTestResultPartnerPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof PageRoute
  '/chat': typeof ChatLayoutRouteWithChildren
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/attachment-test/': typeof AttachmentTestPageRoute
  '/chat/': typeof ChatPageRoute
  '/history/': typeof HistoryPageRoute
  '/intro/': typeof IntroPageRoute
  '/login/': typeof LoginPageRoute
  '/mbti/': typeof MbtiPageRoute
  '/my-attachment-select/': typeof MyAttachmentSelectPageRoute
  '/my-page/': typeof MyPagePageRoute
  '/my-result-preview/': typeof MyResultPreviewPageRoute
  '/partner-attachment-select/': typeof PartnerAttachmentSelectPageRoute
  '/partner-mbti/': typeof PartnerMbtiPageRoute
  '/partner-result-preview/': typeof PartnerResultPreviewPageRoute
  '/partner-status/': typeof PartnerStatusPageRoute
  '/personality-flow-loading/': typeof PersonalityFlowLoadingPageRoute
  '/relationship-status/': typeof RelationshipStatusPageRoute
  '/tutorial/': typeof TutorialPageRoute
  '/attachment-test/question/': typeof AttachmentTestQuestionPageRoute
  '/chat/loading/': typeof ChatLoadingPageRoute
  '/chat/result/': typeof ChatResultPageRoute
  '/history/delete/': typeof HistoryDeletePageRoute
  '/my-page/account-settings/': typeof MyPageAccountSettingsPageRoute
  '/my-page/profile/': typeof MyPageProfilePageRoute
  '/onboarding/nickname/': typeof OnboardingNicknamePageRoute
  '/onboarding/relationship-status/': typeof OnboardingRelationshipStatusPageRoute
  '/onboarding/terms/': typeof OnboardingTermsPageRoute
  '/terms/privacy-policy/': typeof TermsPrivacyPolicyPageRoute
  '/attachment-test/result/my/': typeof AttachmentTestResultMyPageRoute
  '/attachment-test/result/partner/': typeof AttachmentTestResultPartnerPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/onboarding'
    | '/attachment-test'
    | '/chat/'
    | '/history'
    | '/intro'
    | '/login'
    | '/mbti'
    | '/my-attachment-select'
    | '/my-page'
    | '/my-result-preview'
    | '/partner-attachment-select'
    | '/partner-mbti'
    | '/partner-result-preview'
    | '/partner-status'
    | '/personality-flow-loading'
    | '/relationship-status'
    | '/tutorial'
    | '/attachment-test/question'
    | '/chat/loading'
    | '/chat/result'
    | '/history/delete'
    | '/my-page/account-settings'
    | '/my-page/profile'
    | '/onboarding/nickname'
    | '/onboarding/relationship-status'
    | '/onboarding/terms'
    | '/terms/privacy-policy'
    | '/attachment-test/result/my'
    | '/attachment-test/result/partner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/attachment-test'
    | '/chat'
    | '/history'
    | '/intro'
    | '/login'
    | '/mbti'
    | '/my-attachment-select'
    | '/my-page'
    | '/my-result-preview'
    | '/partner-attachment-select'
    | '/partner-mbti'
    | '/partner-result-preview'
    | '/partner-status'
    | '/personality-flow-loading'
    | '/relationship-status'
    | '/tutorial'
    | '/attachment-test/question'
    | '/chat/loading'
    | '/chat/result'
    | '/history/delete'
    | '/my-page/account-settings'
    | '/my-page/profile'
    | '/onboarding/nickname'
    | '/onboarding/relationship-status'
    | '/onboarding/terms'
    | '/terms/privacy-policy'
    | '/attachment-test/result/my'
    | '/attachment-test/result/partner'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/onboarding'
    | '/attachment-test/'
    | '/chat/'
    | '/history/'
    | '/intro/'
    | '/login/'
    | '/mbti/'
    | '/my-attachment-select/'
    | '/my-page/'
    | '/my-result-preview/'
    | '/partner-attachment-select/'
    | '/partner-mbti/'
    | '/partner-result-preview/'
    | '/partner-status/'
    | '/personality-flow-loading/'
    | '/relationship-status/'
    | '/tutorial/'
    | '/attachment-test/question/'
    | '/chat/loading/'
    | '/chat/result/'
    | '/history/delete/'
    | '/my-page/account-settings/'
    | '/my-page/profile/'
    | '/onboarding/nickname/'
    | '/onboarding/relationship-status/'
    | '/onboarding/terms/'
    | '/terms/privacy-policy/'
    | '/attachment-test/result/my/'
    | '/attachment-test/result/partner/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  ChatLayoutRoute: typeof ChatLayoutRouteWithChildren
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
  AttachmentTestPageRoute: typeof AttachmentTestPageRoute
  HistoryPageRoute: typeof HistoryPageRoute
  IntroPageRoute: typeof IntroPageRoute
  LoginPageRoute: typeof LoginPageRoute
  MbtiPageRoute: typeof MbtiPageRoute
  MyAttachmentSelectPageRoute: typeof MyAttachmentSelectPageRoute
  MyPagePageRoute: typeof MyPagePageRoute
  MyResultPreviewPageRoute: typeof MyResultPreviewPageRoute
  PartnerAttachmentSelectPageRoute: typeof PartnerAttachmentSelectPageRoute
  PartnerMbtiPageRoute: typeof PartnerMbtiPageRoute
  PartnerResultPreviewPageRoute: typeof PartnerResultPreviewPageRoute
  PartnerStatusPageRoute: typeof PartnerStatusPageRoute
  PersonalityFlowLoadingPageRoute: typeof PersonalityFlowLoadingPageRoute
  RelationshipStatusPageRoute: typeof RelationshipStatusPageRoute
  TutorialPageRoute: typeof TutorialPageRoute
  AttachmentTestQuestionPageRoute: typeof AttachmentTestQuestionPageRoute
  HistoryDeletePageRoute: typeof HistoryDeletePageRoute
  MyPageAccountSettingsPageRoute: typeof MyPageAccountSettingsPageRoute
  MyPageProfilePageRoute: typeof MyPageProfilePageRoute
  TermsPrivacyPolicyPageRoute: typeof TermsPrivacyPolicyPageRoute
  AttachmentTestResultMyPageRoute: typeof AttachmentTestResultMyPageRoute
  AttachmentTestResultPartnerPageRoute: typeof AttachmentTestResultPartnerPageRoute
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  ChatLayoutRoute: ChatLayoutRouteWithChildren,
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
  AttachmentTestPageRoute: AttachmentTestPageRoute,
  HistoryPageRoute: HistoryPageRoute,
  IntroPageRoute: IntroPageRoute,
  LoginPageRoute: LoginPageRoute,
  MbtiPageRoute: MbtiPageRoute,
  MyAttachmentSelectPageRoute: MyAttachmentSelectPageRoute,
  MyPagePageRoute: MyPagePageRoute,
  MyResultPreviewPageRoute: MyResultPreviewPageRoute,
  PartnerAttachmentSelectPageRoute: PartnerAttachmentSelectPageRoute,
  PartnerMbtiPageRoute: PartnerMbtiPageRoute,
  PartnerResultPreviewPageRoute: PartnerResultPreviewPageRoute,
  PartnerStatusPageRoute: PartnerStatusPageRoute,
  PersonalityFlowLoadingPageRoute: PersonalityFlowLoadingPageRoute,
  RelationshipStatusPageRoute: RelationshipStatusPageRoute,
  TutorialPageRoute: TutorialPageRoute,
  AttachmentTestQuestionPageRoute: AttachmentTestQuestionPageRoute,
  HistoryDeletePageRoute: HistoryDeletePageRoute,
  MyPageAccountSettingsPageRoute: MyPageAccountSettingsPageRoute,
  MyPageProfilePageRoute: MyPageProfilePageRoute,
  TermsPrivacyPolicyPageRoute: TermsPrivacyPolicyPageRoute,
  AttachmentTestResultMyPageRoute: AttachmentTestResultMyPageRoute,
  AttachmentTestResultPartnerPageRoute: AttachmentTestResultPartnerPageRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat",
        "/onboarding",
        "/attachment-test/",
        "/history/",
        "/intro/",
        "/login/",
        "/mbti/",
        "/my-attachment-select/",
        "/my-page/",
        "/my-result-preview/",
        "/partner-attachment-select/",
        "/partner-mbti/",
        "/partner-result-preview/",
        "/partner-status/",
        "/personality-flow-loading/",
        "/relationship-status/",
        "/tutorial/",
        "/attachment-test/question/",
        "/history/delete/",
        "/my-page/account-settings/",
        "/my-page/profile/",
        "/terms/privacy-policy/",
        "/attachment-test/result/my/",
        "/attachment-test/result/partner/"
      ]
    },
    "/": {
      "filePath": "page.tsx"
    },
    "/chat": {
      "filePath": "chat/layout.tsx",
      "children": [
        "/chat/",
        "/chat/loading/",
        "/chat/result/"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding/layout.tsx",
      "children": [
        "/onboarding/nickname/",
        "/onboarding/relationship-status/",
        "/onboarding/terms/"
      ]
    },
    "/attachment-test/": {
      "filePath": "attachment-test/page.tsx"
    },
    "/chat/": {
      "filePath": "chat/page.tsx",
      "parent": "/chat"
    },
    "/history/": {
      "filePath": "history/page.tsx"
    },
    "/intro/": {
      "filePath": "intro/page.tsx"
    },
    "/login/": {
      "filePath": "login/page.tsx"
    },
    "/mbti/": {
      "filePath": "mbti/page.tsx"
    },
    "/my-attachment-select/": {
      "filePath": "my-attachment-select/page.tsx"
    },
    "/my-page/": {
      "filePath": "my-page/page.tsx"
    },
    "/my-result-preview/": {
      "filePath": "my-result-preview/page.tsx"
    },
    "/partner-attachment-select/": {
      "filePath": "partner-attachment-select/page.tsx"
    },
    "/partner-mbti/": {
      "filePath": "partner-mbti/page.tsx"
    },
    "/partner-result-preview/": {
      "filePath": "partner-result-preview/page.tsx"
    },
    "/partner-status/": {
      "filePath": "partner-status/page.tsx"
    },
    "/personality-flow-loading/": {
      "filePath": "personality-flow-loading/page.tsx"
    },
    "/relationship-status/": {
      "filePath": "relationship-status/page.tsx"
    },
    "/tutorial/": {
      "filePath": "tutorial/page.tsx"
    },
    "/attachment-test/question/": {
      "filePath": "attachment-test/question/page.tsx"
    },
    "/chat/loading/": {
      "filePath": "chat/loading/page.tsx",
      "parent": "/chat"
    },
    "/chat/result/": {
      "filePath": "chat/result/page.tsx",
      "parent": "/chat"
    },
    "/history/delete/": {
      "filePath": "history/delete/page.tsx"
    },
    "/my-page/account-settings/": {
      "filePath": "my-page/account-settings/page.tsx"
    },
    "/my-page/profile/": {
      "filePath": "my-page/profile/page.tsx"
    },
    "/onboarding/nickname/": {
      "filePath": "onboarding/nickname/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/relationship-status/": {
      "filePath": "onboarding/relationship-status/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/terms/": {
      "filePath": "onboarding/terms/page.tsx",
      "parent": "/onboarding"
    },
    "/terms/privacy-policy/": {
      "filePath": "terms/privacy-policy/page.tsx"
    },
    "/attachment-test/result/my/": {
      "filePath": "attachment-test/result/my/page.tsx"
    },
    "/attachment-test/result/partner/": {
      "filePath": "attachment-test/result/partner/page.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
