/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as OnboardingLayoutImport } from './app/onboarding/layout'
import { Route as ChatLayoutImport } from './app/chat/layout'
import { Route as PageImport } from './app/page'
import { Route as MyPagePageImport } from './app/my-page/page'
import { Route as LoginPageImport } from './app/login/page'
import { Route as IntroPageImport } from './app/intro/page'
import { Route as HistoryPageImport } from './app/history/page'
import { Route as ChatPageImport } from './app/chat/page'
import { Route as AttachmentTestPageImport } from './app/attachment-test/page'
import { Route as OnboardingTermsPageImport } from './app/onboarding/terms/page'
import { Route as OnboardingPartnerCodePageImport } from './app/onboarding/partner-code/page'
import { Route as OnboardingNicknamePageImport } from './app/onboarding/nickname/page'
import { Route as OnboardingMyCodePageImport } from './app/onboarding/my-code/page'
import { Route as OnboardingCompletePageImport } from './app/onboarding/complete/page'
import { Route as OnboardingAnniversaryPageImport } from './app/onboarding/anniversary/page'
import { Route as HistoryDeletePageImport } from './app/history/delete/page'
import { Route as ChatResultPageImport } from './app/chat/result/page'
import { Route as ChatLoadingPageImport } from './app/chat/loading/page'
import { Route as AttachmentTestQuestionPageImport } from './app/attachment-test/question/page'
import { Route as AttachmentTestResultPartnerPageImport } from './app/attachment-test/result/partner/page'
import { Route as AttachmentTestResultMyPageImport } from './app/attachment-test/result/my/page'

// Create/Update Routes

const OnboardingLayoutRoute = OnboardingLayoutImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const ChatLayoutRoute = ChatLayoutImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MyPagePageRoute = MyPagePageImport.update({
  id: '/my-page/',
  path: '/my-page/',
  getParentRoute: () => rootRoute,
} as any)

const LoginPageRoute = LoginPageImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const IntroPageRoute = IntroPageImport.update({
  id: '/intro/',
  path: '/intro/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryPageRoute = HistoryPageImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const ChatPageRoute = ChatPageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const AttachmentTestPageRoute = AttachmentTestPageImport.update({
  id: '/attachment-test/',
  path: '/attachment-test/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingTermsPageRoute = OnboardingTermsPageImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingPartnerCodePageRoute = OnboardingPartnerCodePageImport.update({
  id: '/partner-code/',
  path: '/partner-code/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingNicknamePageRoute = OnboardingNicknamePageImport.update({
  id: '/nickname/',
  path: '/nickname/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingMyCodePageRoute = OnboardingMyCodePageImport.update({
  id: '/my-code/',
  path: '/my-code/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingCompletePageRoute = OnboardingCompletePageImport.update({
  id: '/complete/',
  path: '/complete/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingAnniversaryPageRoute = OnboardingAnniversaryPageImport.update({
  id: '/anniversary/',
  path: '/anniversary/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const HistoryDeletePageRoute = HistoryDeletePageImport.update({
  id: '/history/delete/',
  path: '/history/delete/',
  getParentRoute: () => rootRoute,
} as any)

const ChatResultPageRoute = ChatResultPageImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const ChatLoadingPageRoute = ChatLoadingPageImport.update({
  id: '/loading/',
  path: '/loading/',
  getParentRoute: () => ChatLayoutRoute,
} as any)

const AttachmentTestQuestionPageRoute = AttachmentTestQuestionPageImport.update({
  id: '/attachment-test/question/',
  path: '/attachment-test/question/',
  getParentRoute: () => rootRoute,
} as any)

const AttachmentTestResultPartnerPageRoute = AttachmentTestResultPartnerPageImport.update({
  id: '/attachment-test/result/partner/',
  path: '/attachment-test/result/partner/',
  getParentRoute: () => rootRoute,
} as any)

const AttachmentTestResultMyPageRoute = AttachmentTestResultMyPageImport.update({
  id: '/attachment-test/result/my/',
  path: '/attachment-test/result/my/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatLayoutImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/attachment-test/': {
      id: '/attachment-test/'
      path: '/attachment-test'
      fullPath: '/attachment-test'
      preLoaderRoute: typeof AttachmentTestPageImport
      parentRoute: typeof rootRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatPageImport
      parentRoute: typeof ChatLayoutImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryPageImport
      parentRoute: typeof rootRoute
    }
    '/intro/': {
      id: '/intro/'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroPageImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginPageImport
      parentRoute: typeof rootRoute
    }
    '/my-page/': {
      id: '/my-page/'
      path: '/my-page'
      fullPath: '/my-page'
      preLoaderRoute: typeof MyPagePageImport
      parentRoute: typeof rootRoute
    }
    '/attachment-test/question/': {
      id: '/attachment-test/question/'
      path: '/attachment-test/question'
      fullPath: '/attachment-test/question'
      preLoaderRoute: typeof AttachmentTestQuestionPageImport
      parentRoute: typeof rootRoute
    }
    '/chat/loading/': {
      id: '/chat/loading/'
      path: '/loading'
      fullPath: '/chat/loading'
      preLoaderRoute: typeof ChatLoadingPageImport
      parentRoute: typeof ChatLayoutImport
    }
    '/chat/result/': {
      id: '/chat/result/'
      path: '/result'
      fullPath: '/chat/result'
      preLoaderRoute: typeof ChatResultPageImport
      parentRoute: typeof ChatLayoutImport
    }
    '/history/delete/': {
      id: '/history/delete/'
      path: '/history/delete'
      fullPath: '/history/delete'
      preLoaderRoute: typeof HistoryDeletePageImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/anniversary/': {
      id: '/onboarding/anniversary/'
      path: '/anniversary'
      fullPath: '/onboarding/anniversary'
      preLoaderRoute: typeof OnboardingAnniversaryPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/complete/': {
      id: '/onboarding/complete/'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompletePageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/my-code/': {
      id: '/onboarding/my-code/'
      path: '/my-code'
      fullPath: '/onboarding/my-code'
      preLoaderRoute: typeof OnboardingMyCodePageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/nickname/': {
      id: '/onboarding/nickname/'
      path: '/nickname'
      fullPath: '/onboarding/nickname'
      preLoaderRoute: typeof OnboardingNicknamePageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/partner-code/': {
      id: '/onboarding/partner-code/'
      path: '/partner-code'
      fullPath: '/onboarding/partner-code'
      preLoaderRoute: typeof OnboardingPartnerCodePageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/terms/': {
      id: '/onboarding/terms/'
      path: '/terms'
      fullPath: '/onboarding/terms'
      preLoaderRoute: typeof OnboardingTermsPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/attachment-test/result/my/': {
      id: '/attachment-test/result/my/'
      path: '/attachment-test/result/my'
      fullPath: '/attachment-test/result/my'
      preLoaderRoute: typeof AttachmentTestResultMyPageImport
      parentRoute: typeof rootRoute
    }
    '/attachment-test/result/partner/': {
      id: '/attachment-test/result/partner/'
      path: '/attachment-test/result/partner'
      fullPath: '/attachment-test/result/partner'
      preLoaderRoute: typeof AttachmentTestResultPartnerPageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface ChatLayoutRouteChildren {
  ChatPageRoute: typeof ChatPageRoute
  ChatLoadingPageRoute: typeof ChatLoadingPageRoute
  ChatResultPageRoute: typeof ChatResultPageRoute
}

const ChatLayoutRouteChildren: ChatLayoutRouteChildren = {
  ChatPageRoute: ChatPageRoute,
  ChatLoadingPageRoute: ChatLoadingPageRoute,
  ChatResultPageRoute: ChatResultPageRoute,
}

const ChatLayoutRouteWithChildren = ChatLayoutRoute._addFileChildren(ChatLayoutRouteChildren)

interface OnboardingLayoutRouteChildren {
  OnboardingAnniversaryPageRoute: typeof OnboardingAnniversaryPageRoute
  OnboardingCompletePageRoute: typeof OnboardingCompletePageRoute
  OnboardingMyCodePageRoute: typeof OnboardingMyCodePageRoute
  OnboardingNicknamePageRoute: typeof OnboardingNicknamePageRoute
  OnboardingPartnerCodePageRoute: typeof OnboardingPartnerCodePageRoute
  OnboardingTermsPageRoute: typeof OnboardingTermsPageRoute
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingAnniversaryPageRoute: OnboardingAnniversaryPageRoute,
  OnboardingCompletePageRoute: OnboardingCompletePageRoute,
  OnboardingMyCodePageRoute: OnboardingMyCodePageRoute,
  OnboardingNicknamePageRoute: OnboardingNicknamePageRoute,
  OnboardingPartnerCodePageRoute: OnboardingPartnerCodePageRoute,
  OnboardingTermsPageRoute: OnboardingTermsPageRoute,
}

const OnboardingLayoutRouteWithChildren = OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/chat': typeof ChatLayoutRouteWithChildren
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/attachment-test': typeof AttachmentTestPageRoute
  '/chat/': typeof ChatPageRoute
  '/history': typeof HistoryPageRoute
  '/intro': typeof IntroPageRoute
  '/login': typeof LoginPageRoute
  '/my-page': typeof MyPagePageRoute
  '/attachment-test/question': typeof AttachmentTestQuestionPageRoute
  '/chat/loading': typeof ChatLoadingPageRoute
  '/chat/result': typeof ChatResultPageRoute
  '/history/delete': typeof HistoryDeletePageRoute
  '/onboarding/anniversary': typeof OnboardingAnniversaryPageRoute
  '/onboarding/complete': typeof OnboardingCompletePageRoute
  '/onboarding/my-code': typeof OnboardingMyCodePageRoute
  '/onboarding/nickname': typeof OnboardingNicknamePageRoute
  '/onboarding/partner-code': typeof OnboardingPartnerCodePageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/attachment-test/result/my': typeof AttachmentTestResultMyPageRoute
  '/attachment-test/result/partner': typeof AttachmentTestResultPartnerPageRoute
}

export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/attachment-test': typeof AttachmentTestPageRoute
  '/chat': typeof ChatPageRoute
  '/history': typeof HistoryPageRoute
  '/intro': typeof IntroPageRoute
  '/login': typeof LoginPageRoute
  '/my-page': typeof MyPagePageRoute
  '/attachment-test/question': typeof AttachmentTestQuestionPageRoute
  '/chat/loading': typeof ChatLoadingPageRoute
  '/chat/result': typeof ChatResultPageRoute
  '/history/delete': typeof HistoryDeletePageRoute
  '/onboarding/anniversary': typeof OnboardingAnniversaryPageRoute
  '/onboarding/complete': typeof OnboardingCompletePageRoute
  '/onboarding/my-code': typeof OnboardingMyCodePageRoute
  '/onboarding/nickname': typeof OnboardingNicknamePageRoute
  '/onboarding/partner-code': typeof OnboardingPartnerCodePageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/attachment-test/result/my': typeof AttachmentTestResultMyPageRoute
  '/attachment-test/result/partner': typeof AttachmentTestResultPartnerPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof PageRoute
  '/chat': typeof ChatLayoutRouteWithChildren
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/attachment-test/': typeof AttachmentTestPageRoute
  '/chat/': typeof ChatPageRoute
  '/history/': typeof HistoryPageRoute
  '/intro/': typeof IntroPageRoute
  '/login/': typeof LoginPageRoute
  '/my-page/': typeof MyPagePageRoute
  '/attachment-test/question/': typeof AttachmentTestQuestionPageRoute
  '/chat/loading/': typeof ChatLoadingPageRoute
  '/chat/result/': typeof ChatResultPageRoute
  '/history/delete/': typeof HistoryDeletePageRoute
  '/onboarding/anniversary/': typeof OnboardingAnniversaryPageRoute
  '/onboarding/complete/': typeof OnboardingCompletePageRoute
  '/onboarding/my-code/': typeof OnboardingMyCodePageRoute
  '/onboarding/nickname/': typeof OnboardingNicknamePageRoute
  '/onboarding/partner-code/': typeof OnboardingPartnerCodePageRoute
  '/onboarding/terms/': typeof OnboardingTermsPageRoute
  '/attachment-test/result/my/': typeof AttachmentTestResultMyPageRoute
  '/attachment-test/result/partner/': typeof AttachmentTestResultPartnerPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/onboarding'
    | '/attachment-test'
    | '/chat/'
    | '/history'
    | '/intro'
    | '/login'
    | '/my-page'
    | '/attachment-test/question'
    | '/chat/loading'
    | '/chat/result'
    | '/history/delete'
    | '/onboarding/anniversary'
    | '/onboarding/complete'
    | '/onboarding/my-code'
    | '/onboarding/nickname'
    | '/onboarding/partner-code'
    | '/onboarding/terms'
    | '/attachment-test/result/my'
    | '/attachment-test/result/partner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/attachment-test'
    | '/chat'
    | '/history'
    | '/intro'
    | '/login'
    | '/my-page'
    | '/attachment-test/question'
    | '/chat/loading'
    | '/chat/result'
    | '/history/delete'
    | '/onboarding/anniversary'
    | '/onboarding/complete'
    | '/onboarding/my-code'
    | '/onboarding/nickname'
    | '/onboarding/partner-code'
    | '/onboarding/terms'
    | '/attachment-test/result/my'
    | '/attachment-test/result/partner'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/onboarding'
    | '/attachment-test/'
    | '/chat/'
    | '/history/'
    | '/intro/'
    | '/login/'
    | '/my-page/'
    | '/attachment-test/question/'
    | '/chat/loading/'
    | '/chat/result/'
    | '/history/delete/'
    | '/onboarding/anniversary/'
    | '/onboarding/complete/'
    | '/onboarding/my-code/'
    | '/onboarding/nickname/'
    | '/onboarding/partner-code/'
    | '/onboarding/terms/'
    | '/attachment-test/result/my/'
    | '/attachment-test/result/partner/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  ChatLayoutRoute: typeof ChatLayoutRouteWithChildren
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
  AttachmentTestPageRoute: typeof AttachmentTestPageRoute
  HistoryPageRoute: typeof HistoryPageRoute
  IntroPageRoute: typeof IntroPageRoute
  LoginPageRoute: typeof LoginPageRoute
  MyPagePageRoute: typeof MyPagePageRoute
  AttachmentTestQuestionPageRoute: typeof AttachmentTestQuestionPageRoute
  HistoryDeletePageRoute: typeof HistoryDeletePageRoute
  AttachmentTestResultMyPageRoute: typeof AttachmentTestResultMyPageRoute
  AttachmentTestResultPartnerPageRoute: typeof AttachmentTestResultPartnerPageRoute
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  ChatLayoutRoute: ChatLayoutRouteWithChildren,
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
  AttachmentTestPageRoute: AttachmentTestPageRoute,
  HistoryPageRoute: HistoryPageRoute,
  IntroPageRoute: IntroPageRoute,
  LoginPageRoute: LoginPageRoute,
  MyPagePageRoute: MyPagePageRoute,
  AttachmentTestQuestionPageRoute: AttachmentTestQuestionPageRoute,
  HistoryDeletePageRoute: HistoryDeletePageRoute,
  AttachmentTestResultMyPageRoute: AttachmentTestResultMyPageRoute,
  AttachmentTestResultPartnerPageRoute: AttachmentTestResultPartnerPageRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/chat",
        "/onboarding",
        "/attachment-test/",
        "/history/",
        "/intro/",
        "/login/",
        "/my-page/",
        "/attachment-test/question/",
        "/history/delete/",
        "/attachment-test/result/my/",
        "/attachment-test/result/partner/"
      ]
    },
    "/": {
      "filePath": "page.tsx"
    },
    "/chat": {
      "filePath": "chat/layout.tsx",
      "children": [
        "/chat/",
        "/chat/loading/",
        "/chat/result/"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding/layout.tsx",
      "children": [
        "/onboarding/anniversary/",
        "/onboarding/complete/",
        "/onboarding/my-code/",
        "/onboarding/nickname/",
        "/onboarding/partner-code/",
        "/onboarding/terms/"
      ]
    },
    "/attachment-test/": {
      "filePath": "attachment-test/page.tsx"
    },
    "/chat/": {
      "filePath": "chat/page.tsx",
      "parent": "/chat"
    },
    "/history/": {
      "filePath": "history/page.tsx"
    },
    "/intro/": {
      "filePath": "intro/page.tsx"
    },
    "/login/": {
      "filePath": "login/page.tsx"
    },
    "/my-page/": {
      "filePath": "my-page/page.tsx"
    },
    "/attachment-test/question/": {
      "filePath": "attachment-test/question/page.tsx"
    },
    "/chat/loading/": {
      "filePath": "chat/loading/page.tsx",
      "parent": "/chat"
    },
    "/chat/result/": {
      "filePath": "chat/result/page.tsx",
      "parent": "/chat"
    },
    "/history/delete/": {
      "filePath": "history/delete/page.tsx"
    },
    "/onboarding/anniversary/": {
      "filePath": "onboarding/anniversary/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/complete/": {
      "filePath": "onboarding/complete/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/my-code/": {
      "filePath": "onboarding/my-code/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/nickname/": {
      "filePath": "onboarding/nickname/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/partner-code/": {
      "filePath": "onboarding/partner-code/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/terms/": {
      "filePath": "onboarding/terms/page.tsx",
      "parent": "/onboarding"
    },
    "/attachment-test/result/my/": {
      "filePath": "attachment-test/result/my/page.tsx"
    },
    "/attachment-test/result/partner/": {
      "filePath": "attachment-test/result/partner/page.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
